In [1]:
import torch 
import os
from torch_geometric.data import DataLoader
from sklearn.metrics import confusion_matrix, f1_score, \
    accuracy_score, precision_score, recall_score, roc_auc_score
import numpy as np
from tqdm import tqdm
import import_ipynb
from Dataset import MoleculeDataset 
import Model
from Model import GNN
import mlflow.pytorch
import matplotlib.pyplot as plt 
import seaborn as sns
import pandas as pd 

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

mlflow.set_tracking_uri("http://localhost:5000")


importing Jupyter notebook from Dataset.ipynb


No normalization for SPS. Feature removed!
No normalization for AvgIpc. Feature removed!


Instructions for updating:
experimental_relax_shapes is deprecated, use reduce_retracing instead


Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'dgl'
D:\Anaconda\Lib\site-packages\transformers\utils\generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Skipped loading modules with pytorch-lightning dependency, missing a dependency. No module named 'lightning'
Skipped loading some Jax models, missing a dependency. No module named 'haiku'


importing Jupyter notebook from Model.ipynb


In [ ]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


def train_one_epoch(epoch, model, train_loader, optimizer, loss_fn):
    
    all_preds = []
    all_labels = []
    running_loss = 0.0
    step = 0
    for _, batch in enumerate(tqdm(train_loader)):
        
        batch.to(device)  
        
        optimizer.zero_grad() 
        
        pred = model(batch.x.float(), 
                                batch.edge_attr.float(),
                                batch.edge_index, 
                                batch.batch) 
        
        loss = loss_fn(torch.squeeze(pred), batch.y.float())
        loss.backward()  
        optimizer.step()  
        
        running_loss += loss.item()
        step += 1
        all_preds.append(np.rint(torch.sigmoid(pred).cpu().detach().numpy()))
        all_labels.append(batch.y.cpu().detach().numpy())
    all_preds = np.concatenate(all_preds).ravel()
    all_labels = np.concatenate(all_labels).ravel()
    calculate_metrics(all_preds, all_labels, epoch, "train")
    return running_loss/step

def test(epoch, model, test_loader, loss_fn):
    all_preds = []
    all_preds_raw = []
    all_labels = []
    running_loss = 0.0
    step = 0
    for batch in test_loader:
        batch.to(device)  
        pred = model(batch.x.float(), 
                        batch.edge_attr.float(),
                        batch.edge_index, 
                        batch.batch) 
        loss = loss_fn(torch.squeeze(pred), batch.y.float())

        running_loss += loss.item()
        step += 1
        all_preds.append(np.rint(torch.sigmoid(pred).cpu().detach().numpy()))
        all_preds_raw.append(torch.sigmoid(pred).cpu().detach().numpy())
        all_labels.append(batch.y.cpu().detach().numpy())
    
    all_preds = np.concatenate(all_preds).ravel()
    all_labels = np.concatenate(all_labels).ravel()
    print(all_preds_raw[0][:10])
    print(all_preds[:10])
    print(all_labels[:10])
    calculate_metrics(all_preds, all_labels, epoch, "test")
    log_conf_matrix(all_preds, all_labels, epoch)
    return running_loss/step

def log_conf_matrix(y_pred, y_true, epoch):
    
    file_path = f'images/cm_{epoch}.png'
    cm = confusion_matrix(y_pred, y_true)
    classes = ["0", "1"]
    df_cfm = pd.DataFrame(cm, index = classes, columns = classes)
    plt.figure(figsize = (10,7))
    cfm_plot = sns.heatmap(df_cfm, annot=True, cmap='Blues', fmt='g')
    cfm_plot.figure.savefig(file_path)
    if(os.path.exists(file_path)):
        mlflow.log_artifact(f"images/cm_{epoch}.png")
    else:
        print("image not found")
    

def calculate_metrics(y_pred, y_true, epoch, type):
    print(f"\n Confusion matrix: \n {confusion_matrix(y_pred, y_true)}")
    print(f"F1 Score: {f1_score(y_true, y_pred)}")
    accuracy = accuracy_score(y_true, y_pred)
    print(f"Accuracy: {accuracy}")
    prec = precision_score(y_true, y_pred)
    rec = recall_score(y_true, y_pred)
    print(f"Precision: {prec}")
    print(f"Recall: {rec}")
    mlflow.log_metric(key=f"Precision-{type}", value=float(prec), step=epoch)
    mlflow.log_metric(key=f"Recall-{type}", value=float(rec), step=epoch)
    mlflow.log_metric(key=f"Accuracy-{type}", value=float(accuracy), step=epoch)
    try:
        roc = roc_auc_score(y_true, y_pred)
        print(f"ROC AUC: {roc}")
        mlflow.log_metric(key=f"ROC-AUC-{type}", value=float(roc), step=epoch)
    except:
        mlflow.log_metric(key=f"ROC-AUC-{type}", value=float(0), step=epoch)
        print(f"ROC AUC: notdefined")


from mango import scheduler, tuner
from mango.tuner import Tuner
from config import HYPERPARAMETERS, BEST_PARAMETERS,SIGNATURE

def run_one_training(params):
    params = params[0]
    with mlflow.start_run() as run:
        
        for key in params.keys():
            mlflow.log_param(key, params[key])

        
        train_dataset = MoleculeDataset(root="data/", filename="HIV_train_oversampled.csv")
        test_dataset = MoleculeDataset(root="data/", filename="HIV_test.csv", test=True)
        params["model_edge_dim"] = train_dataset[0].edge_attr.shape[1]

        
        train_loader = DataLoader(train_dataset, batch_size=params["batch_size"], shuffle=True)
        test_loader = DataLoader(test_dataset, batch_size=params["batch_size"], shuffle=True)

        
        model_params = {k: v for k, v in params.items() if k.startswith("model_")}
        model = GNN(feature_size=train_dataset[0].x.shape[1], model_params=model_params) 
        model = model.to(device)
        print(f"Number of parameters: {count_parameters(model)}")
        mlflow.log_param("num_params", count_parameters(model))

    
        weight = torch.tensor([params["pos_weight"]], dtype=torch.float32).to(device)
        loss_fn = torch.nn.BCEWithLogitsLoss(pos_weight=weight)
        optimizer = torch.optim.SGD(model.parameters(), 
                                    lr=params["learning_rate"],
                                    momentum=params["sgd_momentum"],
                                    weight_decay=params["weight_decay"])
        scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=params["scheduler_gamma"])
        
        
        best_loss = 1000
        early_stopping_counter = 0
        for epoch in range(300): 
            if early_stopping_counter <= 10: 
                
                model.train()
                loss = train_one_epoch(epoch, model, train_loader, optimizer, loss_fn)
                print(f"Epoch {epoch} | Train Loss {loss}")
                mlflow.log_metric(key="Train loss", value=float(loss), step=epoch)

                
                model.eval()
                if epoch % 5 == 0:
                    loss = test(epoch, model, test_loader, loss_fn)
                    print(f"Epoch {epoch} | Test Loss {loss}")
                    mlflow.log_metric(key="Test loss", value=float(loss), step=epoch)
                    
                    
                    if float(loss) < best_loss:
                        best_loss = loss
                        
                        mlflow.pytorch.log_model(model, "model", signature=SIGNATURE)
                        early_stopping_counter = 0
                    else:
                        early_stopping_counter += 1

                scheduler.step()
            else:
                
                return [best_loss]
    print(f"Finishing training with best test loss: {best_loss}")
    return [best_loss]



config = dict()
config["optimizer"] = "Bayesian"
config["num_iteration"] = 100

tuner = Tuner(BEST_PARAMETERS, 
              objective=run_one_training,
              conf_dict=config) 
results = tuner.minimize()

Number of parameters: 365633


100%|██████████| 560/560 [07:36<00:00,  1.23it/s]



 Confusion matrix: 
 [[13649  9068]
 [22201 26716]]
F1 Score: 0.6308308048311118
Accuracy: 0.5634894044727364
Precision: 0.5461496003434388
Recall: 0.7465906550413592
ROC AUC: 0.5636579495569418
Epoch 0 | Train Loss 0.7564117217702525
[[0.4885675 ]
 [0.5022531 ]
 [0.42802837]
 [0.6394342 ]
 [0.42966688]
 [0.50174105]
 [0.6236231 ]
 [0.56727153]
 [0.46092224]
 [0.4380293 ]]
[0. 1. 0. 1. 0. 1. 1. 1. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[2563   32]
 [1271  133]]
F1 Score: 0.1695347355003187
Accuracy: 0.6741685421355339
Precision: 0.09472934472934473
Recall: 0.806060606060606
ROC AUC: 0.737276521079338
Epoch 0 | Test Loss 0.6828329432755709


2024/05/04 23:02:08 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmp1cr1ujcy\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [05:02<00:00,  1.85it/s]



 Confusion matrix: 
 [[23843 12679]
 [12007 23105]]
F1 Score: 0.6517998194538479
Accuracy: 0.6553871066811849
Precision: 0.6580371383002962
Recall: 0.6456796333556897
ROC AUC: 0.6553781709316803
Epoch 1 | Train Loss 0.7056518653673786


100%|██████████| 560/560 [03:35<00:00,  2.60it/s]



 Confusion matrix: 
 [[26091 12621]
 [ 9759 23163]]
F1 Score: 0.6742642563968212
Accuracy: 0.6875785241645029
Precision: 0.7035720794605431
Recall: 0.6473004694835681
ROC AUC: 0.6875414481309053
Epoch 2 | Train Loss 0.6743555527712618


100%|██████████| 560/560 [01:37<00:00,  5.76it/s]



 Confusion matrix: 
 [[27254 12276]
 [ 8596 23508]]
F1 Score: 0.6925524393118078
Accuracy: 0.708629980177011
Precision: 0.7322452030899577
Recall: 0.6569416498993964
ROC AUC: 0.7085824009608558
Epoch 3 | Train Loss 0.6514655580478055


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[27984 12174]
 [ 7866 23610]]
F1 Score: 0.7020517395182873
Accuracy: 0.720244576597705
Precision: 0.7500953107129241
Recall: 0.6597920858484239
ROC AUC: 0.7201889299535007
Epoch 4 | Train Loss 0.6392692943768842


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[28727 12073]
 [ 7123 23711]]
F1 Score: 0.7118496502446786
Accuracy: 0.7320266912360053
Precision: 0.7689887786210028
Recall: 0.6626145763469707
ROC AUC: 0.7319627972390362
Epoch 5 | Train Loss 0.6218759109931332
[[0.28414986]
 [0.3282041 ]
 [0.31853658]
 [0.31301612]
 [0.2993697 ]
 [0.521227  ]
 [0.31519186]
 [0.31480998]
 [0.7125582 ]
 [0.30381814]]
[0. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
[0 0 0 0 0 0 0 0 1 0]

 Confusion matrix: 
 [[3542   75]
 [ 292   90]]
F1 Score: 0.3290676416819013
Accuracy: 0.908227056764191
Precision: 0.2356020942408377
Recall: 0.5454545454545454
ROC AUC: 0.734646938872291
Epoch 5 | Test Loss 0.4705433715134859


2024/05/04 23:16:15 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmpwxq46ga1\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [02:10<00:00,  4.28it/s]



 Confusion matrix: 
 [[29142 11790]
 [ 6708 23994]]
F1 Score: 0.7217760129952169
Accuracy: 0.7417706675600971
Precision: 0.7815126050420168
Recall: 0.670523138832998
ROC AUC: 0.7417050840608505
Epoch 6 | Train Loss 0.611085935149874


100%|██████████| 560/560 [01:39<00:00,  5.65it/s]



 Confusion matrix: 
 [[29523 11655]
 [ 6327 24129]]
F1 Score: 0.7285326086956521
Accuracy: 0.7489739509171622
Precision: 0.79225768321513
Recall: 0.6742957746478874
ROC AUC: 0.748905209499676
Epoch 7 | Train Loss 0.601976845360228


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[29678 11413]
 [ 6172 24371]]
F1 Score: 0.7348741839673135
Accuracy: 0.7545160119496328
Precision: 0.797924237959598
Recall: 0.6810585736642074
ROC AUC: 0.7544483942240144
Epoch 8 | Train Loss 0.5938619931893689


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[29894 11279]
 [ 5956 24505]]
F1 Score: 0.739829421088384
Accuracy: 0.759401959963146
Precision: 0.8044712911591871
Recall: 0.6848032640286161
ROC AUC: 0.7593332917074741
Epoch 9 | Train Loss 0.5889235873839684


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30013 11236]
 [ 5837 24548]]
F1 Score: 0.741978872281582
Accuracy: 0.7616634559008292
Precision: 0.8078986341945039
Recall: 0.6860049183992846
ROC AUC: 0.7615938120587776
Epoch 10 | Train Loss 0.5827072166438614
[[0.2628961 ]
 [0.3433754 ]
 [0.2797899 ]
 [0.29361427]
 [0.44003978]
 [0.32387877]
 [0.30008343]
 [0.28163442]
 [0.29986   ]
 [0.35686162]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3446   71]
 [ 388   94]]
F1 Score: 0.29057187017001546
Accuracy: 0.8852213053263316
Precision: 0.1950207468879668
Recall: 0.5696969696969697
ROC AUC: 0.7342485891781667
Epoch 10 | Test Loss 0.47296447586268187


100%|██████████| 560/560 [01:38<00:00,  5.66it/s]



 Confusion matrix: 
 [[30243 10935]
 [ 5607 24849]]
F1 Score: 0.7502717391304348
Accuracy: 0.769076137029902
Precision: 0.8158983451536643
Recall: 0.6944164989939637
ROC AUC: 0.7690074126768983
Epoch 11 | Train Loss 0.5759233873869691


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30271 10675]
 [ 5579 25109]]
F1 Score: 0.7554759898904801
Accuracy: 0.7730965742524499
Precision: 0.8182025547445255
Recall: 0.7016823161189358
ROC AUC: 0.7730308372784358
Epoch 12 | Train Loss 0.5708696958209787


100%|██████████| 560/560 [01:37<00:00,  5.75it/s]



 Confusion matrix: 
 [[30259 10637]
 [ 5591 25147]]
F1 Score: 0.7560506298668109
Accuracy: 0.7734595303905967
Precision: 0.8181078794976901
Recall: 0.702744243237201
ROC AUC: 0.7733944368208321
Epoch 13 | Train Loss 0.566767877978938


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30468 10591]
 [ 5382 25193]]
F1 Score: 0.7592941424674875
Accuracy: 0.7770192925147277
Precision: 0.8239738348323794
Recall: 0.7040297339593115
ROC AUC: 0.7769521054733795
Epoch 14 | Train Loss 0.5645035727747849


100%|██████████| 560/560 [01:36<00:00,  5.77it/s]



 Confusion matrix: 
 [[30501 10535]
 [ 5349 25249]]
F1 Score: 0.7607182670000905
Accuracy: 0.7782617192953067
Precision: 0.8251846525916726
Recall: 0.7055946791862285
ROC AUC: 0.7781948291328633
Epoch 15 | Train Loss 0.5615098788802113
[[0.3022198 ]
 [0.28040347]
 [0.2549682 ]
 [0.26139045]
 [0.2930632 ]
 [0.27153373]
 [0.2745952 ]
 [0.29251987]
 [0.46132204]
 [0.2769586 ]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3453   61]
 [ 381  104]]
F1 Score: 0.32
Accuracy: 0.889472368092023
Precision: 0.21443298969072164
Recall: 0.6303030303030303
ROC AUC: 0.7654645041968986
Epoch 15 | Test Loss 0.45671479776501656


2024/05/04 23:33:22 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmpn7cuicfn\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:36<00:00,  5.78it/s]



 Confusion matrix: 
 [[30322 10221]
 [ 5528 25563]]
F1 Score: 0.7645009345794391
Accuracy: 0.7801462992433761
Precision: 0.8221993502942974
Recall: 0.7143695506371562
ROC AUC: 0.7800857516086758
Epoch 16 | Train Loss 0.557058171927929


100%|██████████| 560/560 [01:39<00:00,  5.64it/s]



 Confusion matrix: 
 [[30505 10387]
 [ 5345 25397]]
F1 Score: 0.763521029371975
Accuracy: 0.7803836167183181
Precision: 0.826133628261011
Recall: 0.7097306058573665
ROC AUC: 0.780318580474011
Epoch 17 | Train Loss 0.5570900852658919


100%|██████████| 560/560 [01:39<00:00,  5.64it/s]



 Confusion matrix: 
 [[30445 10191]
 [ 5405 25593]]
F1 Score: 0.7664640172501572
Accuracy: 0.7822821565178546
Precision: 0.8256339118652817
Recall: 0.7152079141515761
ROC AUC: 0.782220414537434
Epoch 18 | Train Loss 0.5558383662253619


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30536 10276]
 [ 5314 25508]]
F1 Score: 0.7659370026724319
Accuracy: 0.7823659156266577
Precision: 0.8275906819804036
Recall: 0.7128325508607198
ROC AUC: 0.7823019100189234
Epoch 19 | Train Loss 0.5554512121847698


100%|██████████| 560/560 [01:37<00:00,  5.75it/s]



 Confusion matrix: 
 [[30451 10155]
 [ 5399 25629]]
F1 Score: 0.7671975094294438
Accuracy: 0.7828684702794763
Precision: 0.825995874693825
Recall: 0.7162139503688799
ROC AUC: 0.7828071146544539
Epoch 20 | Train Loss 0.5545877949999911
[[0.2634431 ]
 [0.70558107]
 [0.3083588 ]
 [0.2885681 ]
 [0.28419095]
 [0.27297768]
 [0.29442832]
 [0.26915872]
 [0.28037325]
 [0.40322432]]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 1 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3457   68]
 [ 377   97]]
F1 Score: 0.30359937402190923
Accuracy: 0.8887221805451363
Precision: 0.20464135021097046
Recall: 0.5878787878787879
ROC AUC: 0.7447740313937498
Epoch 20 | Test Loss 0.4544445965439081


2024/05/04 23:41:44 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmp4yf70n1h\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[30553 10253]
 [ 5297 25531]]
F1 Score: 0.7665585780339879
Accuracy: 0.782924309685345
Precision: 0.8281756844427144
Recall: 0.7134752962217751
ROC AUC: 0.7828603817231609
Epoch 21 | Train Loss 0.5533480441996029


100%|██████████| 560/560 [01:37<00:00,  5.76it/s]



 Confusion matrix: 
 [[30541 10032]
 [ 5309 25752]]
F1 Score: 0.7704989154013016
Accuracy: 0.7858419186419856
Precision: 0.8290782653488297
Recall: 0.7196512407780014
ROC AUC: 0.7857809899845376
Epoch 22 | Train Loss 0.5505439787038735


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30522 10071]
 [ 5328 25713]]
F1 Score: 0.7695622895622896
Accuracy: 0.7850322472568891
Precision: 0.8283560452305015
Recall: 0.7185613682092555
ROC AUC: 0.7849710606736654
Epoch 23 | Train Loss 0.5512922403535673


100%|██████████| 560/560 [01:37<00:00,  5.76it/s]



 Confusion matrix: 
 [[30505 10138]
 [ 5345 25646]]
F1 Score: 0.768131785847997
Accuracy: 0.783859619733646
Precision: 0.8275305733922752
Recall: 0.7166890230270512
ROC AUC: 0.7837977890588532
Epoch 24 | Train Loss 0.5504893113992044


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30491 10101]
 [ 5359 25683]]
F1 Score: 0.7686529195223416
Accuracy: 0.7841806963173912
Precision: 0.8273629276464145
Recall: 0.7177230046948356
ROC AUC: 0.7841195218732196
Epoch 25 | Train Loss 0.5513451152614185
[[0.2604792 ]
 [0.3602811 ]
 [0.28211477]
 [0.27771378]
 [0.42510116]
 [0.2608269 ]
 [0.30265376]
 [0.2570871 ]
 [0.33182824]
 [0.45526287]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 1 0]

 Confusion matrix: 
 [[3472   68]
 [ 362   97]]
F1 Score: 0.3108974358974359
Accuracy: 0.8924731182795699
Precision: 0.2113289760348584
Recall: 0.5878787878787879
ROC AUC: 0.746730212927396
Epoch 25 | Test Loss 0.44935741648077965


2024/05/04 23:50:02 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmprk9vawb7\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30464 10074]
 [ 5386 25710]]
F1 Score: 0.7688397129186603
Accuracy: 0.7841806963173912
Precision: 0.8267944430151788
Recall: 0.7184775318578136
ROC AUC: 0.7841202164170519
Epoch 26 | Train Loss 0.5521098723368986


100%|██████████| 560/560 [01:39<00:00,  5.64it/s]



 Confusion matrix: 
 [[30570 10091]
 [ 5280 25693]]
F1 Score: 0.7697469928247226
Accuracy: 0.7854231230979702
Precision: 0.8295289445646208
Recall: 0.7180024591996423
ROC AUC: 0.7853610622358044
Epoch 27 | Train Loss 0.5507892436214856


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30611  9951]
 [ 5239 25833]]
F1 Score: 0.7727952614574609
Accuracy: 0.7879498562135299
Precision: 0.8313916065911432
Recall: 0.7219148222669349
ROC AUC: 0.7878890708266335
Epoch 28 | Train Loss 0.5503981814320599


100%|██████████| 560/560 [01:38<00:00,  5.68it/s]



 Confusion matrix: 
 [[30566 10050]
 [ 5284 25734]]
F1 Score: 0.7704559743720247
Accuracy: 0.7859396376022559
Precision: 0.8296473015668322
Recall: 0.7191482226693494
ROC AUC: 0.785878155965079
Epoch 29 | Train Loss 0.5491888855717012


100%|██████████| 560/560 [01:38<00:00,  5.69it/s]



 Confusion matrix: 
 [[30392 10038]
 [ 5458 25746]]
F1 Score: 0.7686749865647579
Accuracy: 0.7836781416645727
Precision: 0.8250865273682861
Recall: 0.7194835680751174
ROC AUC: 0.7836190504252855
Epoch 30 | Train Loss 0.5515041927141803
[[0.284198  ]
 [0.26680008]
 [0.23124963]
 [0.33792007]
 [0.25417542]
 [0.2833795 ]
 [0.11736098]
 [0.2883288 ]
 [0.43611926]
 [0.30503476]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3459   72]
 [ 375   93]]
F1 Score: 0.29383886255924174
Accuracy: 0.8882220555138785
Precision: 0.1987179487179487
Recall: 0.5636363636363636
ROC AUC: 0.7329136434770237
Epoch 30 | Test Loss 0.45547183603048325


100%|██████████| 560/560 [01:38<00:00,  5.68it/s]



 Confusion matrix: 
 [[30549 10010]
 [ 5301 25774]]
F1 Score: 0.7709956774704976
Accuracy: 0.7862607141860011
Precision: 0.8294127111826227
Recall: 0.7202660406885759
ROC AUC: 0.7861999659509825
Epoch 31 | Train Loss 0.5502848890210901


100%|██████████| 560/560 [01:38<00:00,  5.68it/s]



 Confusion matrix: 
 [[30504 10035]
 [ 5346 25749]]
F1 Score: 0.7700174942807159
Accuracy: 0.7852835245832984
Precision: 0.8280752532561505
Recall: 0.7195674044265593
ROC AUC: 0.7852230327572127
Epoch 32 | Train Loss 0.5502972511840718


100%|██████████| 560/560 [01:37<00:00,  5.77it/s]



 Confusion matrix: 
 [[30532 10148]
 [ 5318 25636]]
F1 Score: 0.7682579639785428
Accuracy: 0.7840969372085881
Precision: 0.8281966789429476
Recall: 0.7164095685222446
ROC AUC: 0.784034630844107
Epoch 33 | Train Loss 0.5505396158567497


100%|██████████| 560/560 [01:37<00:00,  5.77it/s]



 Confusion matrix: 
 [[30520 10071]
 [ 5330 25713]]
F1 Score: 0.7695392580843072
Accuracy: 0.7850043275539548
Precision: 0.8283026769319976
Recall: 0.7185613682092555
ROC AUC: 0.784943166670876
Epoch 34 | Train Loss 0.5503703592611211


100%|██████████| 560/560 [01:37<00:00,  5.77it/s]



 Confusion matrix: 
 [[30637 10079]
 [ 5213 25705]]
F1 Score: 0.7707415070012893
Accuracy: 0.7865259513638775
Precision: 0.8313927162170903
Recall: 0.7183378046054102
ROC AUC: 0.7864631840321333
Epoch 35 | Train Loss 0.5500517227287803
[[0.38189653]
 [0.29168552]
 [0.34510913]
 [0.27287367]
 [0.278366  ]
 [0.2665106 ]
 [0.25920287]
 [0.2768011 ]
 [0.25638327]
 [0.28267598]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3482   72]
 [ 352   93]]
F1 Score: 0.30491803278688523
Accuracy: 0.8939734933733433
Precision: 0.20898876404494382
Recall: 0.5636363636363636
ROC AUC: 0.7359131218286148
Epoch 35 | Test Loss 0.44503912329673767


2024/05/05 00:06:38 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmp81rv4zhj\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:36<00:00,  5.78it/s]



 Confusion matrix: 
 [[30487 10034]
 [ 5363 25750]]
F1 Score: 0.7698402021017385
Accuracy: 0.7850601669598235
Precision: 0.82762832256613
Recall: 0.71959534987704
ROC AUC: 0.7849999064587432
Epoch 36 | Train Loss 0.550130120664835


100%|██████████| 560/560 [01:37<00:00,  5.77it/s]



 Confusion matrix: 
 [[30514 10068]
 [ 5336 25716]]
F1 Score: 0.769525405470106
Accuracy: 0.7849624479995533
Precision: 0.8281592167976298
Recall: 0.7186452045606975
ROC AUC: 0.7849014028382288
Epoch 37 | Train Loss 0.5509858618889536


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30558 10023]
 [ 5292 25761]]
F1 Score: 0.7708604515462991
Accuracy: 0.7862048747801323
Precision: 0.8295816829291855
Recall: 0.7199027498323273
ROC AUC: 0.7861438435354104
Epoch 38 | Train Loss 0.5494245994303908


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30586 10132]
 [ 5264 25652]]
F1 Score: 0.769175412293853
Accuracy: 0.7850741268112907
Precision: 0.8297321775132618
Recall: 0.7168566957299352
ROC AUC: 0.785011332523266
Epoch 39 | Train Loss 0.5505604510328599


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30522 10029]
 [ 5328 25755]]
F1 Score: 0.7703351428955988
Accuracy: 0.7856185610185108
Precision: 0.8285879741337708
Recall: 0.7197350771294433
ROC AUC: 0.7855579151337593
Epoch 40 | Train Loss 0.5482920142156738
[[0.2436205 ]
 [0.2851057 ]
 [0.27536902]
 [0.24897638]
 [0.25216573]
 [0.24255653]
 [0.27356067]
 [0.25517026]
 [0.4447488 ]
 [0.27390498]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3495   73]
 [ 339   92]]
F1 Score: 0.3087248322147651
Accuracy: 0.8969742435608902
Precision: 0.21345707656612528
Recall: 0.5575757575757576
ROC AUC: 0.7345781761274719
Epoch 40 | Test Loss 0.44243290554732084


2024/05/05 00:14:56 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmpqdmoqil8\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30509 10052]
 [ 5341 25732]]
F1 Score: 0.7697623285519841
Accuracy: 0.7851160063656922
Precision: 0.8281144401892319
Recall: 0.7190923317683882
ROC AUC: 0.7850552314351006
Epoch 41 | Train Loss 0.5494931866015706


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30527 10068]
 [ 5323 25716]]
F1 Score: 0.7696751118626819
Accuracy: 0.7851439260686266
Precision: 0.8285060730049293
Recall: 0.7186452045606975
ROC AUC: 0.7850827138563597
Epoch 42 | Train Loss 0.5502868525151695


100%|██████████| 560/560 [01:37<00:00,  5.76it/s]



 Confusion matrix: 
 [[30578  9932]
 [ 5272 25852]]
F1 Score: 0.7727625993902075
Accuracy: 0.7877544182929893
Precision: 0.8306130317439918
Recall: 0.7224457858260676
ROC AUC: 0.7876943015601746
Epoch 43 | Train Loss 0.5498342197388411


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[30546 10023]
 [ 5304 25761]]
F1 Score: 0.7707220751245345
Accuracy: 0.7860373565625262
Precision: 0.829261226460647
Recall: 0.7199027498323273
ROC AUC: 0.785976479518674
Epoch 44 | Train Loss 0.549933322040098


100%|██████████| 560/560 [01:37<00:00,  5.75it/s]



 Confusion matrix: 
 [[30498 10110]
 [ 5352 25674]]
F1 Score: 0.7685675797036371
Accuracy: 0.7841527766144568
Precision: 0.8274995165345195
Recall: 0.7174714956405097
ROC AUC: 0.7840913963558197
Epoch 45 | Train Loss 0.5502399628183672
[[0.28215626]
 [0.26514035]
 [0.27521896]
 [0.6389267 ]
 [0.3322986 ]
 [0.30287346]
 [0.3713086 ]
 [0.86497384]
 [0.31083778]
 [0.29306397]]
[0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3464   62]
 [ 370  103]]
F1 Score: 0.322884012539185
Accuracy: 0.891972993248312
Precision: 0.21775898520084566
Recall: 0.6242424242424243
ROC AUC: 0.7638687342912696
Epoch 45 | Test Loss 0.4497504699975252


100%|██████████| 560/560 [01:42<00:00,  5.46it/s]



 Confusion matrix: 
 [[30637  9962]
 [ 5213 25822]]
F1 Score: 0.772893937353148
Accuracy: 0.7881592539855375
Precision: 0.8320283550829708
Recall: 0.7216074223116477
ROC AUC: 0.788097992885252
Epoch 46 | Train Loss 0.548185824070658


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30579 10018]
 [ 5271 25766]]
F1 Score: 0.7711946843058319
Accuracy: 0.786567830918279
Precision: 0.8301704417308374
Recall: 0.7200424770847306
ROC AUC: 0.7865065941909009
Epoch 47 | Train Loss 0.548388844994562


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30547  9958]
 [ 5303 25826]]
F1 Score: 0.7719277270485556
Accuracy: 0.7869587067593601
Precision: 0.8296443830511742
Recall: 0.7217192041135703
ROC AUC: 0.7868986536606902
Epoch 48 | Train Loss 0.5486226064818246


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[30461 10119]
 [ 5389 25665]]
F1 Score: 0.7679763009066698
Accuracy: 0.7835106234469665
Precision: 0.8264635795710698
Recall: 0.7172199865861838
ROC AUC: 0.7834496027770529
Epoch 49 | Train Loss 0.5516437594911882


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[30551 10000]
 [ 5299 25784]]
F1 Score: 0.7712025363781836
Accuracy: 0.7864282324036073
Precision: 0.8295209600102951
Recall: 0.7205454951933825
ROC AUC: 0.7863675872061753
Epoch 50 | Train Loss 0.5481610177350896
[[0.39664775]
 [0.2983146 ]
 [0.27698714]
 [0.52574515]
 [0.55032086]
 [0.5389045 ]
 [0.26413247]
 [0.27262428]
 [0.37978873]
 [0.2746301 ]]
[0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3458   61]
 [ 376  104]]
F1 Score: 0.32248062015503876
Accuracy: 0.8907226806701676
Precision: 0.21666666666666667
Recall: 0.6303030303030303
ROC AUC: 0.7661165647081141
Epoch 50 | Test Loss 0.4534378834068775


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[30499  9965]
 [ 5351 25819]]
F1 Score: 0.771245930041521
Accuracy: 0.7861909149286651
Precision: 0.8283285210137953
Recall: 0.7215235859602057
ROC AUC: 0.7861313885170622
Epoch 51 | Train Loss 0.5488976943173579


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30530  9971]
 [ 5320 25813]]
F1 Score: 0.7714930436212025
Accuracy: 0.7865399112153447
Precision: 0.8291202261266181
Recall: 0.7213559132573217
ROC AUC: 0.7864799092088561
Epoch 52 | Train Loss 0.5481846826417106


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[30501 10046]
 [ 5349 25738]]
F1 Score: 0.7697806223923674
Accuracy: 0.7850880866627579
Precision: 0.8279345063853057
Recall: 0.719260004471272
ROC AUC: 0.785027491775385
Epoch 53 | Train Loss 0.5497231412678957


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[30489  9997]
 [ 5361 25787]]
F1 Score: 0.7705432379131059
Accuracy: 0.7856046011670436
Precision: 0.8278862206241171
Recall: 0.7206293315448244
ROC AUC: 0.7855447912954248
Epoch 54 | Train Loss 0.5490721082580942


100%|██████████| 560/560 [01:37<00:00,  5.75it/s]



 Confusion matrix: 
 [[30502 10065]
 [ 5348 25719]]
F1 Score: 0.7694424915109722
Accuracy: 0.7848368093363487
Precision: 0.8278559242926578
Recall: 0.7187290409121395
ROC AUC: 0.7847759569972135
Epoch 55 | Train Loss 0.5504923604428769
[[0.3477729 ]
 [0.26830775]
 [0.29957092]
 [0.5785208 ]
 [0.32544956]
 [0.2280839 ]
 [0.6023749 ]
 [0.73334235]
 [0.46198773]
 [0.7083294 ]]
[0. 0. 0. 1. 0. 0. 1. 1. 0. 1.]
[0 0 0 0 0 0 0 0 0 1]

 Confusion matrix: 
 [[3463   69]
 [ 371   96]]
F1 Score: 0.3037974683544304
Accuracy: 0.8899724931232809
Precision: 0.20556745182012848
Recall: 0.5818181818181818
ROC AUC: 0.7425262009769051
Epoch 55 | Test Loss 0.4528855327516794


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30519 10079]
 [ 5331 25705]]
F1 Score: 0.7693804250224483
Accuracy: 0.7848786888907502
Precision: 0.8282317308931564
Recall: 0.7183378046054102
ROC AUC: 0.7848174378675586
Epoch 56 | Train Loss 0.5506724487457957


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[30423 10027]
 [ 5427 25757]]
F1 Score: 0.7692330665392426
Accuracy: 0.7842644554261943
Precision: 0.8259684453565931
Recall: 0.7197909680304047
ROC AUC: 0.7842051074461647
Epoch 57 | Train Loss 0.5475125798689467


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30619 10040]
 [ 5231 25744]]
F1 Score: 0.7712518162345152
Accuracy: 0.7868191082446883
Precision: 0.8311218724778047
Recall: 0.719427677174156
ROC AUC: 0.7867570742914015
Epoch 58 | Train Loss 0.5499761307878154


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30570 10099]
 [ 5280 25685]]
F1 Score: 0.7695995445624654
Accuracy: 0.7853114442862328
Precision: 0.8294849023090586
Recall: 0.717778895595797
ROC AUC: 0.7852492804338819
Epoch 59 | Train Loss 0.5512692639870304


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[30515 10091]
 [ 5335 25693]]
F1 Score: 0.7691133329342035
Accuracy: 0.7846553312672753
Precision: 0.8280585277813588
Recall: 0.7180024591996423
ROC AUC: 0.784593977159096
Epoch 60 | Train Loss 0.5496568365288632
[[0.29721817]
 [0.26085374]
 [0.26291174]
 [0.29120377]
 [0.46123722]
 [0.23481752]
 [0.27724195]
 [0.5840735 ]
 [0.3094058 ]
 [0.26524213]]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0 0 0 0 0 0 0 1 0 0]

 Confusion matrix: 
 [[3471   70]
 [ 363   95]]
F1 Score: 0.3049759229534511
Accuracy: 0.8917229307326832
Precision: 0.2074235807860262
Recall: 0.5757575757575758
ROC AUC: 0.7405391947645468
Epoch 60 | Test Loss 0.4492830475792289


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30422 10074]
 [ 5428 25710]]
F1 Score: 0.7683571919548131
Accuracy: 0.7835943825557696
Precision: 0.8256792343760035
Recall: 0.7184775318578136
ROC AUC: 0.7835344423584745
Epoch 61 | Train Loss 0.5521291005824294


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[30572 10061]
 [ 5278 25723]]
F1 Score: 0.770322677247885
Accuracy: 0.78586983834492
Precision: 0.8297474275023387
Recall: 0.7188408227140621
ROC AUC: 0.7858081379958037
Epoch 62 | Train Loss 0.550973123258778


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30510 10094]
 [ 5340 25690]]
F1 Score: 0.7690005088753854
Accuracy: 0.7845436524555379
Precision: 0.8279084756687077
Recall: 0.7179186228482003
ROC AUC: 0.7844823239764013
Epoch 63 | Train Loss 0.5500674513833863


100%|██████████| 560/560 [01:37<00:00,  5.76it/s]



 Confusion matrix: 
 [[30496 10013]
 [ 5354 25771]]
F1 Score: 0.7703298509916453
Accuracy: 0.785478962503839
Precision: 0.8279839357429719
Recall: 0.7201822043371339
ROC AUC: 0.7854188567013424
Epoch 64 | Train Loss 0.5493095126003027


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[30502  9976]
 [ 5348 25808]]
F1 Score: 0.7710785778308933
Accuracy: 0.7860792361169278
Precision: 0.8283476697907305
Recall: 0.7212161860049184
ROC AUC: 0.7860195295436029
Epoch 65 | Train Loss 0.5482909357973508
[[0.26764745]
 [0.23983447]
 [0.3494339 ]
 [0.32151377]
 [0.36064622]
 [0.2283736 ]
 [0.55152625]
 [0.32120264]
 [0.26624736]
 [0.25665957]]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3469   66]
 [ 365   99]]
F1 Score: 0.314785373608903
Accuracy: 0.892223055763941
Precision: 0.21336206896551724
Recall: 0.6
ROC AUC: 0.7523995826812729
Epoch 65 | Test Loss 0.45297276973724365


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[30475 10003]
 [ 5375 25781]]
F1 Score: 0.7702718852703914
Accuracy: 0.7853254041377
Precision: 0.8274810630376171
Recall: 0.7204616588419406
ROC AUC: 0.785265696924457
Epoch 66 | Train Loss 0.5514601227960416


100%|██████████| 560/560 [01:38<00:00,  5.67it/s]



 Confusion matrix: 
 [[30481 10019]
 [ 5369 25765]]
F1 Score: 0.7700469230999134
Accuracy: 0.7851858056230282
Precision: 0.827551872550909
Recall: 0.72001453163425
ROC AUC: 0.78512581532898
Epoch 67 | Train Loss 0.5515627661453826


100%|██████████| 560/560 [01:38<00:00,  5.69it/s]



 Confusion matrix: 
 [[30579 10103]
 [ 5271 25681]]
F1 Score: 0.7696295852313594
Accuracy: 0.7853812435435686
Precision: 0.8297040578960971
Recall: 0.7176671137938744
ROC AUC: 0.7853189125454728
Epoch 68 | Train Loss 0.5486488051712513


100%|██████████| 560/560 [01:38<00:00,  5.67it/s]



 Confusion matrix: 
 [[30506 10034]
 [ 5344 25750]]
F1 Score: 0.7700589132450133
Accuracy: 0.7853254041377
Precision: 0.8281340451534058
Recall: 0.71959534987704
ROC AUC: 0.7852648994852425
Epoch 69 | Train Loss 0.5506574095359871


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[30495 10057]
 [ 5355 25727]]
F1 Score: 0.7695091675889092
Accuracy: 0.7848507691878158
Precision: 0.8277137893314459
Recall: 0.7189526045159848
ROC AUC: 0.7847901097893731
Epoch 70 | Train Loss 0.5508694184145757
[[0.22228761]
 [0.28930438]
 [0.2503531 ]
 [0.2716566 ]
 [0.32996383]
 [0.27446592]
 [0.27809206]
 [0.2652328 ]
 [0.25029024]
 [0.31403083]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3456   66]
 [ 378   99]]
F1 Score: 0.308411214953271
Accuracy: 0.8889722430607652
Precision: 0.20754716981132076
Recall: 0.6
ROC AUC: 0.7507042253521127
Epoch 70 | Test Loss 0.4549055593088269


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30649  9966]
 [ 5201 25818]]
F1 Score: 0.7729592982351091
Accuracy: 0.788270932797275
Precision: 0.8323285728102131
Recall: 0.721495640509725
ROC AUC: 0.788209466001027
Epoch 71 | Train Loss 0.5480258309947593


100%|██████████| 560/560 [01:39<00:00,  5.65it/s]



 Confusion matrix: 
 [[30474 10041]
 [ 5376 25743]]
F1 Score: 0.7695619030536748
Accuracy: 0.78478096993048
Precision: 0.8272438060348983
Recall: 0.7193997317236754
ROC AUC: 0.7847207863639298
Epoch 72 | Train Loss 0.5495858601693596


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[30582  9993]
 [ 5268 25791]]
F1 Score: 0.7716888829047169
Accuracy: 0.7869587067593601
Precision: 0.830387327344731
Recall: 0.7207411133467472
ROC AUC: 0.7868977533260932
Epoch 73 | Train Loss 0.5498270055545228


100%|██████████| 560/560 [01:37<00:00,  5.75it/s]



 Confusion matrix: 
 [[30402 10071]
 [ 5448 25713]]
F1 Score: 0.7681828366569572
Accuracy: 0.7833570650808276
Precision: 0.8251660729758352
Recall: 0.7185613682092555
ROC AUC: 0.7832974205063014
Epoch 74 | Train Loss 0.5531993744096586


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30469 10060]
 [ 5381 25724]]
F1 Score: 0.7691548685135075
Accuracy: 0.7844459334952676
Precision: 0.8270053046134062
Recall: 0.7188687681645428
ROC AUC: 0.7843855695773899
Epoch 75 | Train Loss 0.5510078073612281
[[0.6984431 ]
 [0.2922964 ]
 [0.27409837]
 [0.23814243]
 [0.31651536]
 [0.26561236]
 [0.541017  ]
 [0.34580812]
 [0.2726796 ]
 [0.27322045]]
[1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3467   66]
 [ 367   99]]
F1 Score: 0.3137876386687797
Accuracy: 0.8917229307326832
Precision: 0.21244635193133046
Recall: 0.6
ROC AUC: 0.7521387584767867
Epoch 75 | Test Loss 0.44891258142888546


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30483 10094]
 [ 5367 25690]]
F1 Score: 0.7686898759743271
Accuracy: 0.784166736465924
Precision: 0.8271887175193998
Recall: 0.7179186228482003
ROC AUC: 0.7841057549387445
Epoch 76 | Train Loss 0.5509337021836213


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30516 10107]
 [ 5334 25677]]
F1 Score: 0.768830002245677
Accuracy: 0.7844459334952676
Precision: 0.8279965173648061
Recall: 0.7175553319919518
ROC AUC: 0.7843843605566453
Epoch 77 | Train Loss 0.5488600539309638


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30610 10020]
 [ 5240 25764]]
F1 Score: 0.7715158411690722
Accuracy: 0.7869726666108272
Precision: 0.830989549735518
Recall: 0.7199865861837693
ROC AUC: 0.7869110057836559
Epoch 78 | Train Loss 0.5484156418059554


100%|██████████| 560/560 [01:37<00:00,  5.76it/s]



 Confusion matrix: 
 [[30555 10055]
 [ 5295 25729]]
F1 Score: 0.7702370973536103
Accuracy: 0.785716279978781
Precision: 0.8293256833419288
Recall: 0.7190084954169461
ROC AUC: 0.7856548753235358
Epoch 79 | Train Loss 0.5495658811713968


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30441  9986]
 [ 5409 25798]]
F1 Score: 0.7701930110014777
Accuracy: 0.7850880866627579
Precision: 0.8266735027397699
Recall: 0.7209367315001117
ROC AUC: 0.7850290352061228
Epoch 80 | Train Loss 0.5494338637483972
[[0.28365633]
 [0.27777058]
 [0.2925246 ]
 [0.33510846]
 [0.2547957 ]
 [0.28727233]
 [0.26458195]
 [0.27102906]
 [0.25077853]
 [0.24966416]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3464   70]
 [ 370   95]]
F1 Score: 0.30158730158730157
Accuracy: 0.8899724931232809
Precision: 0.20430107526881722
Recall: 0.5757575757575758
ROC AUC: 0.7396263100488453
Epoch 80 | Test Loss 0.45216050185263157


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30595 10062]
 [ 5255 25722]]
F1 Score: 0.7705696439538053
Accuracy: 0.786176955077198
Precision: 0.8303580075539917
Recall: 0.7188128772635815
ROC AUC: 0.7861149463026416
Epoch 81 | Train Loss 0.5505534761186157


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30428 10036]
 [ 5422 25748]]
F1 Score: 0.7691250709442304
Accuracy: 0.7842086160203255
Precision: 0.8260506897658004
Recall: 0.7195394589760787
ROC AUC: 0.7841490879259752
Epoch 82 | Train Loss 0.5521148018006767


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[30493 10049]
 [ 5357 25735]]
F1 Score: 0.7696333512769903
Accuracy: 0.7849345282966189
Precision: 0.8277048758523092
Recall: 0.7191761681198301
ROC AUC: 0.7848739975885064
Epoch 83 | Train Loss 0.5501878654318196


100%|██████████| 560/560 [01:37<00:00,  5.75it/s]



 Confusion matrix: 
 [[30604 10082]
 [ 5246 25702]]
F1 Score: 0.770305101001019
Accuracy: 0.786023396711059
Precision: 0.8304898539485589
Recall: 0.7182539682539683
ROC AUC: 0.7859610148103873
Epoch 84 | Train Loss 0.547743440845183


100%|██████████| 560/560 [01:37<00:00,  5.76it/s]



 Confusion matrix: 
 [[30501 10007]
 [ 5349 25777]]
F1 Score: 0.7704976834553878
Accuracy: 0.7856325208699779
Precision: 0.8281500995951937
Recall: 0.7203498770400178
ROC AUC: 0.7855724280597579
Epoch 85 | Train Loss 0.5506639946252108
[[0.2352639 ]
 [0.30777156]
 [0.2723292 ]
 [0.26360646]
 [0.27923754]
 [0.28226396]
 [0.30452266]
 [0.27554086]
 [0.3331096 ]
 [0.25699633]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3489   72]
 [ 345   93]]
F1 Score: 0.30845771144278605
Accuracy: 0.8957239309827457
Precision: 0.21232876712328766
Recall: 0.5636363636363636
ROC AUC: 0.7368260065443164
Epoch 85 | Test Loss 0.44347344525158405


100%|██████████| 560/560 [01:37<00:00,  5.76it/s]



 Confusion matrix: 
 [[30381  9992]
 [ 5469 25792]]
F1 Score: 0.7693936908046834
Accuracy: 0.784166736465924
Precision: 0.8250535811394389
Recall: 0.7207690587972279
ROC AUC: 0.7841083787709988
Epoch 86 | Train Loss 0.5495618290134838


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30556 10019]
 [ 5294 25765]]
F1 Score: 0.770910940562213
Accuracy: 0.7862327944830667
Precision: 0.8295502108889533
Recall: 0.72001453163425
ROC AUC: 0.7861718404335825
Epoch 87 | Train Loss 0.5499480301248175


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30507 10016]
 [ 5343 25768]]
F1 Score: 0.7704013752896329
Accuracy: 0.7855906413155764
Precision: 0.8282601009289319
Recall: 0.7200983679856919
ROC AUC: 0.7855303555409631
Epoch 88 | Train Loss 0.5512986206582614


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[30490 10010]
 [ 5360 25774]]
F1 Score: 0.7703159090229834
Accuracy: 0.7854370829494374
Precision: 0.8278409455900302
Recall: 0.7202660406885759
ROC AUC: 0.7853770928686952
Epoch 89 | Train Loss 0.5500805592962674


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[30569 10094]
 [ 5281 25690]]
F1 Score: 0.769680173769755
Accuracy: 0.7853672836921015
Precision: 0.8294856478641309
Recall: 0.7179186228482003
ROC AUC: 0.7853051970586886
Epoch 90 | Train Loss 0.5494904692683901
[[0.28348604]
 [0.26087883]
 [0.2594347 ]
 [0.27974582]
 [0.5833761 ]
 [0.27092022]
 [0.30158702]
 [0.30437577]
 [0.34200343]
 [0.27085686]]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3455   65]
 [ 379  100]]
F1 Score: 0.3105590062111801
Accuracy: 0.8889722430607652
Precision: 0.20876826722338204
Recall: 0.6060606060606061
ROC AUC: 0.7536041162801725
Epoch 90 | Test Loss 0.4555145911872387


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30590 10138]
 [ 5260 25646]]
F1 Score: 0.7691108112160743
Accuracy: 0.7850462071083564
Precision: 0.829806510062771
Recall: 0.7166890230270512
ROC AUC: 0.7849832841774028
Epoch 91 | Train Loss 0.5489280535706452


100%|██████████| 560/560 [01:37<00:00,  5.75it/s]



 Confusion matrix: 
 [[30438 10088]
 [ 5412 25696]]
F1 Score: 0.7682832027746218
Accuracy: 0.783622302258704
Precision: 0.826025459688826
Recall: 0.7180862955510843
ROC AUC: 0.783561976227425
Epoch 92 | Train Loss 0.550162607591067


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30569 10006]
 [ 5281 25778]]
F1 Score: 0.7712999117334649
Accuracy: 0.7865957506212133
Precision: 0.8299687691168421
Recall: 0.7203778224904985
ROC AUC: 0.7865347968798377
Epoch 93 | Train Loss 0.548188713831561


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[30533 10093]
 [ 5317 25691]]
F1 Score: 0.7692837465564739
Accuracy: 0.7848786888907502
Precision: 0.8285281217750258
Recall: 0.717946568298681
ROC AUC: 0.7848170777337198
Epoch 94 | Train Loss 0.5500732033912624


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[30585  9963]
 [ 5265 25821]]
F1 Score: 0.7722745625841184
Accuracy: 0.787419381857777
Precision: 0.8306311522872032
Recall: 0.721579476861167
ROC AUC: 0.7873587760874873
Epoch 95 | Train Loss 0.5515597597828933
[[0.30960014]
 [0.32022342]
 [0.36942342]
 [0.32655963]
 [0.28681222]
 [0.46808565]
 [0.536492  ]
 [0.25998577]
 [0.26697168]
 [0.30318084]]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3488   73]
 [ 346   92]]
F1 Score: 0.30514096185737977
Accuracy: 0.8952238059514879
Precision: 0.2100456621004566
Recall: 0.5575757575757576
ROC AUC: 0.7336652914117702
Epoch 95 | Test Loss 0.4446164984256029
Number of parameters: 365633


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[12173  8135]
 [23677 27649]]
F1 Score: 0.6348065664102858
Accuracy: 0.5559092051260575
Precision: 0.5386938393796517
Recall: 0.7726637603398167
ROC AUC: 0.556108728147593
Epoch 0 | Train Loss 0.7605644110058035
[[0.4291585 ]
 [0.44790593]
 [0.43912277]
 [0.4295132 ]
 [0.42388868]
 [0.41957432]
 [0.43210313]
 [0.4487078 ]
 [0.42573762]
 [0.43476653]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3034   60]
 [ 800  105]]
F1 Score: 0.19626168224299065
Accuracy: 0.7849462365591398
Precision: 0.11602209944751381
Recall: 0.6363636363636364
ROC AUC: 0.7138521363873476
Epoch 0 | Test Loss 0.6519604697823524


2024/05/05 01:47:24 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmp25m430nn\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[26007 14398]
 [ 9843 21386]]
F1 Score: 0.6382642173906554
Accuracy: 0.6615992405840802
Precision: 0.6848121937942298
Recall: 0.5976414039794321
ROC AUC: 0.6615403672616825
Epoch 1 | Train Loss 0.6981190351503236


100%|██████████| 560/560 [01:38<00:00,  5.69it/s]



 Confusion matrix: 
 [[29544 15655]
 [ 6306 20129]]
F1 Score: 0.6470370787058616
Accuracy: 0.6934277019292515
Precision: 0.7614526196330622
Recall: 0.5625139727252403
ROC AUC: 0.6933071955676411
Epoch 2 | Train Loss 0.6728341448519911


100%|██████████| 560/560 [01:38<00:00,  5.68it/s]



 Confusion matrix: 
 [[30394 15343]
 [ 5456 20441]]
F1 Score: 0.6627972957636874
Accuracy: 0.7096490493341151
Precision: 0.7893192261651929
Recall: 0.5712329532752068
ROC AUC: 0.7095216370281195
Epoch 3 | Train Loss 0.6522102653980255


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[30079 14136]
 [ 5771 21648]]
F1 Score: 0.6850307738556715
Accuracy: 0.72210123684284
Precision: 0.7895255115066195
Recall: 0.6049631120053656
ROC AUC: 0.7219934109538683
Epoch 4 | Train Loss 0.6390275449625084


100%|██████████| 560/560 [01:38<00:00,  5.68it/s]



 Confusion matrix: 
 [[30464 13869]
 [ 5386 21915]]
F1 Score: 0.6947768883252754
Accuracy: 0.7312030599994416
Precision: 0.8027178491630343
Recall: 0.6124245472837022
ROC AUC: 0.7310937241299962
Epoch 5 | Train Loss 0.6306919171341828
[[0.37813586]
 [0.35178256]
 [0.35346922]
 [0.36940473]
 [0.42368865]
 [0.36535877]
 [0.38332084]
 [0.44344226]
 [0.35580766]
 [0.355842  ]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 1 1 0 0 0 0 0]

 Confusion matrix: 
 [[3551   71]
 [ 283   94]]
F1 Score: 0.34686346863468637
Accuracy: 0.9114778694673669
Precision: 0.2493368700265252
Recall: 0.5696969696969697
ROC AUC: 0.747941859913691
Epoch 5 | Test Loss 0.5271926335990429


2024/05/05 01:55:46 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmphleobhvj\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:38<00:00,  5.69it/s]



 Confusion matrix: 
 [[30718 13388]
 [ 5132 22396]]
F1 Score: 0.7074804144553954
Accuracy: 0.7414635508278192
Precision: 0.8135716361522813
Recall: 0.6258663089649005
ROC AUC: 0.7413571433248491
Epoch 6 | Train Loss 0.6191110864281655


100%|██████████| 560/560 [01:39<00:00,  5.63it/s]



 Confusion matrix: 
 [[30654 13318]
 [ 5196 22466]]
F1 Score: 0.708192793871954
Accuracy: 0.7415473099366223
Precision: 0.8121610874123346
Recall: 0.6278224904985469
ROC AUC: 0.7414426260024115
Epoch 7 | Train Loss 0.6143107357834067


100%|██████████| 560/560 [01:39<00:00,  5.65it/s]



 Confusion matrix: 
 [[30810 13149]
 [ 5040 22635]]
F1 Score: 0.7133739895050348
Accuracy: 0.7460842616634559
Precision: 0.8178861788617886
Recall: 0.6325452716297787
ROC AUC: 0.7459797487856006
Epoch 8 | Train Loss 0.6086201850324869


100%|██████████| 560/560 [01:39<00:00,  5.66it/s]



 Confusion matrix: 
 [[30800 12853]
 [ 5050 22931]]
F1 Score: 0.7192346898768917
Accuracy: 0.7500767791830695
Precision: 0.8195203888352811
Recall: 0.6408171249720546
ROC AUC: 0.7499762054427916
Epoch 9 | Train Loss 0.6012251947075129


100%|██████████| 560/560 [01:38<00:00,  5.67it/s]



 Confusion matrix: 
 [[31034 12941]
 [ 4816 22843]]
F1 Score: 0.7201109657487822
Accuracy: 0.7521149174972779
Precision: 0.8258794605734119
Recall: 0.6383579253297563
ROC AUC: 0.7520102039480023
Epoch 10 | Train Loss 0.5989042679114002
[[0.3530358 ]
 [0.33204868]
 [0.3328964 ]
 [0.33222216]
 [0.3413985 ]
 [0.34474725]
 [0.33082455]
 [0.338528  ]
 [0.33288184]
 [0.33371305]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3539   66]
 [ 295   99]]
F1 Score: 0.3542039355992845
Accuracy: 0.9097274318579645
Precision: 0.2512690355329949
Recall: 0.6
ROC AUC: 0.7615284298382892
Epoch 10 | Test Loss 0.5013757972046733


2024/05/05 02:04:12 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmpn3gfzlw4\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[30865 12701]
 [ 4985 23083]]
F1 Score: 0.7230157238614295
Accuracy: 0.7531060669514477
Precision: 0.8223956106598261
Recall: 0.6450648334451151
ROC AUC: 0.7530066147699774
Epoch 11 | Train Loss 0.5958809117121356


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31102 12682]
 [ 4748 23102]]
F1 Score: 0.7260898261935443
Accuracy: 0.7566797889270458
Precision: 0.8295152603231598
Recall: 0.6455957970042477
ROC AUC: 0.7565775358800876
Epoch 12 | Train Loss 0.5917958983885391


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31049 12457]
 [ 4801 23327]]
F1 Score: 0.7299724621354363
Accuracy: 0.7590808833794008
Precision: 0.82931598407281
Recall: 0.6518835233623966
ROC AUC: 0.7589822079852431
Epoch 13 | Train Loss 0.5899289591503994


100%|██████████| 560/560 [01:38<00:00,  5.68it/s]



 Confusion matrix: 
 [[31007 12415]
 [ 4843 23369]]
F1 Score: 0.7303268954309644
Accuracy: 0.7590808833794008
Precision: 0.8283354600879058
Recall: 0.6530572322825844
ROC AUC: 0.7589832883867593
Epoch 14 | Train Loss 0.5884565775947911


100%|██████████| 560/560 [01:38<00:00,  5.69it/s]



 Confusion matrix: 
 [[31114 12317]
 [ 4736 23467]]
F1 Score: 0.7334927407129572
Accuracy: 0.7619426529301728
Precision: 0.8320746019926958
Recall: 0.6557958864296892
ROC AUC: 0.7618449446095445
Epoch 15 | Train Loss 0.5845159211861236
[[0.33186236]
 [0.34855855]
 [0.3247066 ]
 [0.32166007]
 [0.3194673 ]
 [0.31944424]
 [0.32879764]
 [0.33428884]
 [0.3191826 ]
 [0.31890705]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3576   70]
 [ 258   95]]
F1 Score: 0.3667953667953668
Accuracy: 0.9179794948737184
Precision: 0.26912181303116145
Recall: 0.5757575757575758
ROC AUC: 0.7542324655000711
Epoch 15 | Test Loss 0.48415232729166746


2024/05/05 02:12:34 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmp3q16_7rc\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[31061 12461]
 [ 4789 23323]]
F1 Score: 0.7300300488293476
Accuracy: 0.7591925621911383
Precision: 0.829645702902675
Recall: 0.6517717415604739
ROC AUC: 0.759093681101018
Epoch 16 | Train Loss 0.5840588056083237


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31153 12318]
 [ 4697 23466]]
F1 Score: 0.7339202777299951
Accuracy: 0.7624731272859256
Precision: 0.8332208926605831
Recall: 0.6557679409792085
ROC AUC: 0.7623749049386976
Epoch 17 | Train Loss 0.5827454633478607


100%|██████████| 560/560 [01:38<00:00,  5.68it/s]



 Confusion matrix: 
 [[31136 12328]
 [ 4714 23456]]
F1 Score: 0.7335272226913093
Accuracy: 0.7620962112963118
Precision: 0.8326588569400071
Recall: 0.6554884864744019
ROC AUC: 0.7619980786625845
Epoch 18 | Train Loss 0.5819345910634314


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[31159 12208]
 [ 4691 23576]]
F1 Score: 0.736163369814679
Accuracy: 0.7640924700561186
Precision: 0.8340467683164113
Recall: 0.6588419405320813
ROC AUC: 0.7639955867235023
Epoch 19 | Train Loss 0.5830669397754329


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31141 12221]
 [ 4709 23563]]
F1 Score: 0.7357000124890721
Accuracy: 0.763659714660636
Precision: 0.8334394453876627
Recall: 0.6584786496758328
ROC AUC: 0.7635628952702734
Epoch 20 | Train Loss 0.5826963908970356
[[0.37622455]
 [0.31504288]
 [0.38164502]
 [0.3362342 ]
 [0.41265997]
 [0.31558105]
 [0.31647468]
 [0.31936878]
 [0.3158683 ]
 [0.32778275]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3573   72]
 [ 261   93]]
F1 Score: 0.3583815028901734
Accuracy: 0.9167291822955739
Precision: 0.2627118644067797
Recall: 0.5636363636363636
ROC AUC: 0.7477806231327357
Epoch 20 | Test Loss 0.4795608352869749


2024/05/05 02:20:55 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmp0wrrbsdv\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31171 12296]
 [ 4679 23488]]
F1 Score: 0.7345623993369923
Accuracy: 0.7630315213446129
Precision: 0.8338836226790215
Recall: 0.6563827408897831
ROC AUC: 0.7629333509190895
Epoch 21 | Train Loss 0.5812604773789645


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31158 12126]
 [ 4692 23658]]
F1 Score: 0.7377677986715314
Accuracy: 0.7652232180249602
Precision: 0.8344973544973545
Recall: 0.6611334674714956
ROC AUC: 0.7651274031918149
Epoch 22 | Train Loss 0.5788452461894069


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31143 12101]
 [ 4707 23683]]
F1 Score: 0.7380870757627699
Accuracy: 0.765362816539632
Precision: 0.834202183867559
Recall: 0.6618321037335122
ROC AUC: 0.7652675163019025
Epoch 23 | Train Loss 0.5791187021349158


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31118 12159]
 [ 4732 23625]]
F1 Score: 0.7366582996835098
Accuracy: 0.764204148867856
Precision: 0.833127622809183
Recall: 0.6602112676056338
ROC AUC: 0.7641084232030958
Epoch 24 | Train Loss 0.5828159089067153


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31170 12179]
 [ 4680 23605]]
F1 Score: 0.7368618208493968
Accuracy: 0.7646508641148059
Precision: 0.834541276294856
Recall: 0.6596523585960206
ROC AUC: 0.7645542127708137
Epoch 25 | Train Loss 0.5787472199648619
[[0.31498682]
 [0.31383762]
 [0.31362507]
 [0.32664534]
 [0.67723805]
 [0.7120923 ]
 [0.38253832]
 [0.84805524]
 [0.3228329 ]
 [0.31482494]]
[0. 0. 0. 0. 1. 1. 0. 1. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3558   72]
 [ 276   93]]
F1 Score: 0.348314606741573
Accuracy: 0.9129782445611403
Precision: 0.25203252032520324
Recall: 0.5636363636363636
ROC AUC: 0.7458244415990893
Epoch 25 | Test Loss 0.4793826546519995


2024/05/05 02:29:16 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmpa0ttcb3d\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31133 12104]
 [ 4717 23680]]
F1 Score: 0.7379130895436343
Accuracy: 0.7651813384705587
Precision: 0.8338909039687291
Recall: 0.6617482673820702
ROC AUC: 0.7650861281122345
Epoch 26 | Train Loss 0.5798756332269737


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31151 12121]
 [ 4699 23663]]
F1 Score: 0.7377856764256538
Accuracy: 0.7651952983220258
Precision: 0.8343205697764614
Recall: 0.6612731947238989
ROC AUC: 0.7650996378082534
Epoch 27 | Train Loss 0.5776249719517571


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31170 12103]
 [ 4680 23681]]
F1 Score: 0.7383584067347415
Accuracy: 0.7657118128263115
Precision: 0.8349846620358944
Recall: 0.6617762128325508
ROC AUC: 0.7656161398890787
Epoch 28 | Train Loss 0.5800744030624628


100%|██████████| 560/560 [01:38<00:00,  5.69it/s]



 Confusion matrix: 
 [[31075 12137]
 [ 4775 23647]]
F1 Score: 0.7365978257483724
Accuracy: 0.7639109919870453
Precision: 0.831996340862712
Recall: 0.6608260675162083
ROC AUC: 0.763816102098411
Epoch 29 | Train Loss 0.5804585390325103


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31065 12138]
 [ 4785 23646]]
F1 Score: 0.7364634431207662
Accuracy: 0.7637574336209063
Precision: 0.8316977946607577
Recall: 0.6607981220657277
ROC AUC: 0.7636626593592237
Epoch 30 | Train Loss 0.578162037900516
[[0.322256  ]
 [0.31409368]
 [0.32337055]
 [0.4772839 ]
 [0.5758698 ]
 [0.3322138 ]
 [0.31650198]
 [0.31992823]
 [0.31444874]
 [0.3154673 ]]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3562   70]
 [ 272   95]]
F1 Score: 0.3571428571428571
Accuracy: 0.9144786196549137
Precision: 0.25885558583106266
Recall: 0.5757575757575758
ROC AUC: 0.7524066960686678
Epoch 30 | Test Loss 0.4806967880576849


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31113 12086]
 [ 4737 23698]]
F1 Score: 0.7380370295395443
Accuracy: 0.7651534187676243
Precision: 0.8334095305081766
Recall: 0.6622512854907221
ROC AUC: 0.7650586971386665
Epoch 31 | Train Loss 0.5793469909046377


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31161 12157]
 [ 4689 23627]]
F1 Score: 0.737191887675507
Accuracy: 0.7648323421838792
Precision: 0.8344045769176437
Recall: 0.6602671585065951
ROC AUC: 0.7647360897135486
Epoch 32 | Train Loss 0.5782561648637057


100%|██████████| 560/560 [01:38<00:00,  5.69it/s]



 Confusion matrix: 
 [[31163 12134]
 [ 4687 23650]]
F1 Score: 0.7376678467272814
Accuracy: 0.7651813384705587
Precision: 0.834597875569044
Recall: 0.6609099038676504
ROC AUC: 0.7650853563968656
Epoch 33 | Train Loss 0.5803346038396869


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31207 12095]
 [ 4643 23689]]
F1 Score: 0.7389419177740346
Accuracy: 0.7663400061423347
Precision: 0.8361216998446985
Recall: 0.6619997764363962
ROC AUC: 0.7662439607426053
Epoch 34 | Train Loss 0.5786414766950266


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31193 12118]
 [ 4657 23666]]
F1 Score: 0.7383281076949475
Accuracy: 0.765823491638049
Precision: 0.8355753274723723
Recall: 0.6613570310753409
ROC AUC: 0.7657273300425518
Epoch 35 | Train Loss 0.5804156819092375
[[0.31756815]
 [0.49490032]
 [0.37753835]
 [0.32077125]
 [0.42795292]
 [0.33271736]
 [0.31474409]
 [0.31832564]
 [0.34211203]
 [0.31418464]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 1 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3552   69]
 [ 282   96]]
F1 Score: 0.3535911602209944
Accuracy: 0.9122280570142536
Precision: 0.25396825396825395
Recall: 0.5818181818181818
ROC AUC: 0.7541328780765401
Epoch 35 | Test Loss 0.48191347904503345


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[31191 12085]
 [ 4659 23699]]
F1 Score: 0.7389541953790029
Accuracy: 0.7662562470335316
Precision: 0.83570773679385
Recall: 0.6622792309412028
ROC AUC: 0.7661605359726935
Epoch 36 | Train Loss 0.5774910267442465


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31168 12091]
 [ 4682 23693]]
F1 Score: 0.7385713617730949
Accuracy: 0.7658514113409833
Precision: 0.8349955947136564
Recall: 0.6621115582383188
ROC AUC: 0.7657559185891734
Epoch 37 | Train Loss 0.5783155633402722


100%|██████████| 560/560 [01:38<00:00,  5.68it/s]



 Confusion matrix: 
 [[31245 12107]
 [ 4605 23677]]
F1 Score: 0.739144007742016
Accuracy: 0.7667029622804813
Precision: 0.8371755887136695
Recall: 0.6616644310306282
ROC AUC: 0.76660627409272
Epoch 38 | Train Loss 0.5772555966462408


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31090 12117]
 [ 4760 23667]]
F1 Score: 0.7371634143682547
Accuracy: 0.7643995867883966
Precision: 0.8325535582368875
Recall: 0.6613849765258216
ROC AUC: 0.7643047616241381
Epoch 39 | Train Loss 0.5787770906197173


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31162 12132]
 [ 4688 23652]]
F1 Score: 0.7376957145530536
Accuracy: 0.7651952983220258
Precision: 0.8345800988002823
Recall: 0.6609657947686117
ROC AUC: 0.7650993548459516
Epoch 40 | Train Loss 0.5785921352782419
[[0.37722817]
 [0.34566838]
 [0.34583595]
 [0.6112427 ]
 [0.42692855]
 [0.35965428]
 [0.31866866]
 [0.31453317]
 [0.31852025]
 [0.3316437 ]]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3567   70]
 [ 267   95]]
F1 Score: 0.3605313092979127
Accuracy: 0.9157289322330583
Precision: 0.26243093922651933
Recall: 0.5757575757575758
ROC AUC: 0.7530587565798833
Epoch 40 | Test Loss 0.4794902903959155


100%|██████████| 560/560 [01:38<00:00,  5.69it/s]



 Confusion matrix: 
 [[31200 12043]
 [ 4650 23741]]
F1 Score: 0.7398831320607714
Accuracy: 0.7669681994583578
Precision: 0.836215702159135
Recall: 0.6634529398613905
ROC AUC: 0.7668729134453396
Epoch 41 | Train Loss 0.5780008203216962


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31178 12115]
 [ 4672 23669]]
F1 Score: 0.738214424951267
Accuracy: 0.7656559734204428
Precision: 0.8351504886912953
Recall: 0.6614408674267829
ROC AUC: 0.7655600431973524
Epoch 42 | Train Loss 0.577632884574788


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31101 12123]
 [ 4749 23661]]
F1 Score: 0.7371716982895598
Accuracy: 0.7644693860457324
Precision: 0.8328405491024288
Recall: 0.6612173038229376
ROC AUC: 0.7643743422880379
Epoch 43 | Train Loss 0.5787718604185752


100%|██████████| 560/560 [01:38<00:00,  5.66it/s]



 Confusion matrix: 
 [[31133 12098]
 [ 4717 23686]]
F1 Score: 0.738031065480549
Accuracy: 0.7652650975793618
Precision: 0.8339259937330563
Recall: 0.6619159400849541
ROC AUC: 0.7651699644636765
Epoch 44 | Train Loss 0.5790741454809905


100%|██████████| 560/560 [01:38<00:00,  5.67it/s]



 Confusion matrix: 
 [[31111 12118]
 [ 4739 23666]]
F1 Score: 0.7373849101871037
Accuracy: 0.7646787838177401
Precision: 0.8331631754972716
Recall: 0.6613570310753409
ROC AUC: 0.7645836759281864
Epoch 45 | Train Loss 0.5797823166740792
[[0.3985114 ]
 [0.31416914]
 [0.31314278]
 [0.31893015]
 [0.375423  ]
 [0.31947342]
 [0.32919967]
 [0.31519902]
 [0.3250603 ]
 [0.35286304]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3555   70]
 [ 279   95]]
F1 Score: 0.35250463821892397
Accuracy: 0.9127281820455114
Precision: 0.2540106951871658
Recall: 0.5757575757575758
ROC AUC: 0.7514938113529662
Epoch 45 | Test Loss 0.482410429045558


100%|██████████| 560/560 [01:38<00:00,  5.68it/s]



 Confusion matrix: 
 [[31080 12092]
 [ 4770 23692]]
F1 Score: 0.7375400803162843
Accuracy: 0.7646089845604043
Precision: 0.8324081231115171
Recall: 0.6620836127878381
ROC AUC: 0.7645146097411994
Epoch 46 | Train Loss 0.5795751143779073


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31095 12078]
 [ 4755 23706]]
F1 Score: 0.7379873920149429
Accuracy: 0.7650138202529525
Precision: 0.8329292716348687
Recall: 0.6624748490945674
ROC AUC: 0.7649194329154845
Epoch 47 | Train Loss 0.5775934589760644


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31139 12154]
 [ 4711 23630]]
F1 Score: 0.7369980506822613
Accuracy: 0.7645671050060028
Precision: 0.8337743904590522
Recall: 0.6603509948580372
ROC AUC: 0.7644711738585861
Epoch 48 | Train Loss 0.5786846173128911


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31204 12129]
 [ 4646 23655]]
F1 Score: 0.738238277287977
Accuracy: 0.765823491638049
Precision: 0.8358361895339387
Recall: 0.6610496311200537
ROC AUC: 0.7657270470802501
Epoch 49 | Train Loss 0.5778697607240506


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[31116 12092]
 [ 4734 23692]]
F1 Score: 0.7379535897835228
Accuracy: 0.7651115392132227
Precision: 0.8334623232252164
Recall: 0.6620836127878381
ROC AUC: 0.7650167017914087
Epoch 50 | Train Loss 0.5785901815231357
[[0.38192254]
 [0.9139028 ]
 [0.31469983]
 [0.3263422 ]
 [0.3752913 ]
 [0.3113933 ]
 [0.32710177]
 [0.3152208 ]
 [0.36880678]
 [0.31349397]]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 1 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3563   70]
 [ 271   95]]
F1 Score: 0.3578154425612053
Accuracy: 0.9147286821705426
Precision: 0.25956284153005466
Recall: 0.5757575757575758
ROC AUC: 0.7525371081709109
Epoch 50 | Test Loss 0.482346479780972


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31208 12102]
 [ 4642 23682]]
F1 Score: 0.7388157484245337
Accuracy: 0.7662562470335316
Precision: 0.8361107188250247
Recall: 0.6618041582830315
ROC AUC: 0.7661600986673178
Epoch 51 | Train Loss 0.5788953455963305


100%|██████████| 560/560 [01:38<00:00,  5.67it/s]



 Confusion matrix: 
 [[31180 12110]
 [ 4670 23674]]
F1 Score: 0.7383358283433135
Accuracy: 0.7657536923807131
Precision: 0.8352384984476432
Recall: 0.6615805946791862
ROC AUC: 0.7656578008263434
Epoch 52 | Train Loss 0.5776332884494747


100%|██████████| 560/560 [01:39<00:00,  5.65it/s]



 Confusion matrix: 
 [[31053 12025]
 [ 4797 23759]]
F1 Score: 0.7385452284737333
Accuracy: 0.7651673786190915
Precision: 0.8320142877153663
Recall: 0.6639559579700425
ROC AUC: 0.7650742132946446
Epoch 53 | Train Loss 0.5792642094194889


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31162 12064]
 [ 4688 23720]]
F1 Score: 0.7390329012961117
Accuracy: 0.7661445682217941
Precision: 0.8349760630808223
Recall: 0.6628660854012967
ROC AUC: 0.7660495001622941
Epoch 54 | Train Loss 0.5799320964408773


100%|██████████| 560/560 [01:38<00:00,  5.69it/s]



 Confusion matrix: 
 [[31192 12141]
 [ 4658 23643]]
F1 Score: 0.7378637746742607
Accuracy: 0.7654884552028366
Precision: 0.8354121762481891
Recall: 0.6607142857142857
ROC AUC: 0.7653920103606295
Epoch 55 | Train Loss 0.5787247826478311
[[0.34917766]
 [0.4412232 ]
 [0.31254733]
 [0.31542248]
 [0.31040046]
 [0.3730923 ]
 [0.76589406]
 [0.3281939 ]
 [0.3193451 ]
 [0.31553233]]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3554   69]
 [ 280   96]]
F1 Score: 0.35489833641404805
Accuracy: 0.9127281820455114
Precision: 0.2553191489361702
Recall: 0.5818181818181818
ROC AUC: 0.7543937022810262
Epoch 55 | Test Loss 0.4805914629250765


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31074 12148]
 [ 4776 23636]]
F1 Score: 0.7363698672814504
Accuracy: 0.7637434737694391
Precision: 0.8319020132338448
Recall: 0.660518667560921
ROC AUC: 0.7636484551193726
Epoch 56 | Train Loss 0.5797636387071439


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[31160 12160]
 [ 4690 23624]]
F1 Score: 0.7371212830353522
Accuracy: 0.7647765027780105
Precision: 0.834357561630289
Recall: 0.6601833221551532
ROC AUC: 0.7646802245364329
Epoch 57 | Train Loss 0.5783633925552879


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31162 12082]
 [ 4688 23702]]
F1 Score: 0.7386792158818213
Accuracy: 0.7658932908953848
Precision: 0.8348714336033815
Recall: 0.6623630672926447
ROC AUC: 0.7657979911079682
Epoch 58 | Train Loss 0.5797940749675036


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31095 12103]
 [ 4755 23681]]
F1 Score: 0.7374961071317346
Accuracy: 0.764664823966273
Precision: 0.8327823885215924
Recall: 0.6617762128325508
ROC AUC: 0.7645701147844762
Epoch 59 | Train Loss 0.5794238681771926


100%|██████████| 560/560 [01:37<00:00,  5.75it/s]



 Confusion matrix: 
 [[31244 12173]
 [ 4606 23611]]
F1 Score: 0.737832221371541
Accuracy: 0.7657676522321802
Precision: 0.8367650707020591
Recall: 0.6598200312989045
ROC AUC: 0.7656701272254633
Epoch 60 | Train Loss 0.5787652636745146
[[0.4034029 ]
 [0.33319646]
 [0.3330426 ]
 [0.31293255]
 [0.3135286 ]
 [0.7968019 ]
 [0.31428275]
 [0.37942782]
 [0.31654552]
 [0.86023915]]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
[0 0 0 0 0 0 0 0 0 1]

 Confusion matrix: 
 [[3570   70]
 [ 264   95]]
F1 Score: 0.3625954198473283
Accuracy: 0.916479119779945
Precision: 0.2646239554317549
Recall: 0.5757575757575758
ROC AUC: 0.7534499928866126
Epoch 60 | Test Loss 0.4784613074734807


2024/05/05 03:27:13 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmpucj7_1nf\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:37<00:00,  5.76it/s]



 Confusion matrix: 
 [[31178 12084]
 [ 4672 23700]]
F1 Score: 0.7388241162167218
Accuracy: 0.7660887288159254
Precision: 0.8353306076413365
Recall: 0.6623071763916835
ROC AUC: 0.7659931976798027
Epoch 61 | Train Loss 0.5784905996705805


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31146 12089]
 [ 4704 23695]]
F1 Score: 0.7383575089977096
Accuracy: 0.7655722143116397
Precision: 0.8343603648015775
Recall: 0.6621674491392802
ROC AUC: 0.7654770300089706
Epoch 62 | Train Loss 0.578100351829614


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31199 12139]
 [ 4651 23645]]
F1 Score: 0.7379837702871411
Accuracy: 0.7656140938660413
Precision: 0.8356304778060504
Recall: 0.6607701766152471
ROC AUC: 0.7655175848208733
Epoch 63 | Train Loss 0.5799895150320871


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[31195 12039]
 [ 4655 23745]]
F1 Score: 0.7399040259254643
Accuracy: 0.7669542396068906
Precision: 0.8360915492957747
Recall: 0.6635647216633133
ROC AUC: 0.7668590693393275
Epoch 64 | Train Loss 0.5784163070044347


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31209 12105]
 [ 4641 23679]]
F1 Score: 0.7387682515911643
Accuracy: 0.7662283273305972
Precision: 0.8361228813559322
Recall: 0.6617203219315896
ROC AUC: 0.7661321274929915
Epoch 65 | Train Loss 0.5785298279885734
[[0.31594193]
 [0.31764314]
 [0.3203764 ]
 [0.43805185]
 [0.35925007]
 [0.32391408]
 [0.31532913]
 [0.37948462]
 [0.61268485]
 [0.35105065]]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3551   69]
 [ 283   96]]
F1 Score: 0.35294117647058826
Accuracy: 0.9119779944986247
Precision: 0.2532981530343008
Recall: 0.5818181818181818
ROC AUC: 0.7540024659742969
Epoch 65 | Test Loss 0.48417026922106743


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[31152 12124]
 [ 4698 23660]]
F1 Score: 0.7377381434941224
Accuracy: 0.7651673786190915
Precision: 0.8343324635023627
Recall: 0.661189358372457
ROC AUC: 0.7650716666339271
Epoch 66 | Train Loss 0.5784349000879696


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[31079 12175]
 [ 4771 23609]]
F1 Score: 0.735895517735802
Accuracy: 0.7634363570371612
Precision: 0.8318886539816772
Recall: 0.6597641403979432
ROC AUC: 0.7633409265448573
Epoch 67 | Train Loss 0.5785618785768747


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31092 12122]
 [ 4758 23662]]
F1 Score: 0.7370880318983241
Accuracy: 0.764357707233995
Precision: 0.8325826882477129
Recall: 0.6612452492734183
ROC AUC: 0.7642627920007259
Epoch 68 | Train Loss 0.578301641451461


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[31108 12162]
 [ 4742 23622]]
F1 Score: 0.7364843798715471
Accuracy: 0.7640226707987827
Precision: 0.8328162459455648
Recall: 0.6601274312541918
ROC AUC: 0.7639270350134278
Epoch 69 | Train Loss 0.5803053666438375


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31089 12102]
 [ 4761 23682]]
F1 Score: 0.7374468681395674
Accuracy: 0.7645950247089371
Precision: 0.8326125936082692
Recall: 0.6618041582830315
ROC AUC: 0.7645004055013485
Epoch 70 | Train Loss 0.5769969245684998
[[0.31153294]
 [0.42704546]
 [0.3155049 ]
 [0.31551152]
 [0.33294934]
 [0.3249357 ]
 [0.32974732]
 [0.32126695]
 [0.32773158]
 [0.3181172 ]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3569   72]
 [ 265   93]]
F1 Score: 0.3556405353728489
Accuracy: 0.9157289322330583
Precision: 0.25977653631284914
Recall: 0.5636363636363636
ROC AUC: 0.7472589747237635
Epoch 70 | Test Loss 0.4806414069607854


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31130 12081]
 [ 4720 23703]]
F1 Score: 0.7383307116046536
Accuracy: 0.7654605354999022
Precision: 0.8339373042958168
Recall: 0.6623910127431254
ROC AUC: 0.7653656597885782
Epoch 71 | Train Loss 0.579013393925769


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31116 12133]
 [ 4734 23651]]
F1 Score: 0.7371472206205489
Accuracy: 0.7645391853030684
Precision: 0.8332217720627092
Recall: 0.660937849318131
ROC AUC: 0.7644438200565551
Epoch 72 | Train Loss 0.5796883945486375


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31084 12061]
 [ 4766 23723]]
F1 Score: 0.7381948874332924
Accuracy: 0.7650975793617556
Precision: 0.8327073607357226
Recall: 0.6629499217527387
ROC AUC: 0.7650035522292286
Epoch 73 | Train Loss 0.5788827502301761


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31059 12101]
 [ 4791 23683]]
F1 Score: 0.7371222260263314
Accuracy: 0.7641901890163889
Precision: 0.8317412376202852
Recall: 0.6618321037335122
ROC AUC: 0.7640959681847477
Epoch 74 | Train Loss 0.580104690257992


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31150 12072]
 [ 4700 23712]]
F1 Score: 0.7387376160508443
Accuracy: 0.7658653711924505
Precision: 0.8345769393214135
Recall: 0.6626425217974514
ROC AUC: 0.765770354343635
Epoch 75 | Train Loss 0.5780380688075508
[[0.6052732 ]
 [0.31305274]
 [0.31159806]
 [0.31512785]
 [0.32610285]
 [0.40235254]
 [0.44090086]
 [0.33298084]
 [0.3594372 ]
 [0.61840117]]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0 0 0 0 0 0 0 1 0 0]

 Confusion matrix: 
 [[3562   69]
 [ 272   96]]
F1 Score: 0.36022514071294554
Accuracy: 0.9147286821705426
Precision: 0.2608695652173913
Recall: 0.5818181818181818
ROC AUC: 0.7554369990989709
Epoch 75 | Test Loss 0.48236100003123283


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31068 12105]
 [ 4782 23679]]
F1 Score: 0.7371468596777958
Accuracy: 0.7642599882737248
Precision: 0.8319806050384737
Recall: 0.6617203219315896
ROC AUC: 0.7641656002963387
Epoch 76 | Train Loss 0.5799849211637463


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31107 12163]
 [ 4743 23621]]
F1 Score: 0.7364532019704433
Accuracy: 0.7639947510958484
Precision: 0.8327809899873079
Recall: 0.6600994858037111
ROC AUC: 0.7638991152867929
Epoch 77 | Train Loss 0.5779494860342571


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31024 12128]
 [ 4826 23656]]
F1 Score: 0.7361902094420067
Accuracy: 0.7633246782254237
Precision: 0.8305596517098518
Recall: 0.6610775765705343
ROC AUC: 0.7632305595544443
Epoch 78 | Train Loss 0.5817800137081317


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31079 12175]
 [ 4771 23609]]
F1 Score: 0.735895517735802
Accuracy: 0.7634363570371612
Precision: 0.8318886539816772
Recall: 0.6597641403979432
ROC AUC: 0.7633409265448573
Epoch 79 | Train Loss 0.5794302491205079


100%|██████████| 560/560 [01:38<00:00,  5.68it/s]



 Confusion matrix: 
 [[31114 12023]
 [ 4736 23761]]
F1 Score: 0.7392853253683047
Accuracy: 0.7660468492615239
Precision: 0.8338070674106046
Recall: 0.6640118488710038
ROC AUC: 0.765952925830202
Epoch 80 | Train Loss 0.5795821356454066
[[0.31308913]
 [0.65107834]
 [0.7792675 ]
 [0.32542124]
 [0.38921604]
 [0.32566953]
 [0.3142991 ]
 [0.33089823]
 [0.34727338]
 [0.32620665]]
[0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
[0 0 1 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3557   70]
 [ 277   95]]
F1 Score: 0.3538175046554935
Accuracy: 0.9132283070767692
Precision: 0.2553763440860215
Recall: 0.5757575757575758
ROC AUC: 0.7517546355574525
Epoch 80 | Test Loss 0.47971322294324636


100%|██████████| 560/560 [01:38<00:00,  5.66it/s]



 Confusion matrix: 
 [[31063 12124]
 [ 4787 23660]]
F1 Score: 0.736715915990721
Accuracy: 0.7639249518385124
Precision: 0.8317221499630892
Recall: 0.661189358372457
ROC AUC: 0.7638303835097989
Epoch 81 | Train Loss 0.579021812762533


100%|██████████| 560/560 [01:38<00:00,  5.69it/s]



 Confusion matrix: 
 [[31184 12117]
 [ 4666 23667]]
F1 Score: 0.7382441474180014
Accuracy: 0.7657118128263115
Precision: 0.8353157095965835
Recall: 0.6613849765258216
ROC AUC: 0.7656157797552399
Epoch 82 | Train Loss 0.5803482031183583


100%|██████████| 560/560 [01:38<00:00,  5.68it/s]



 Confusion matrix: 
 [[31024 12137]
 [ 4826 23647]]
F1 Score: 0.7360131970057737
Accuracy: 0.763199039562219
Precision: 0.8305060934920803
Recall: 0.6608260675162083
ROC AUC: 0.7631048050272813
Epoch 83 | Train Loss 0.5801978293806315


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31131 12096]
 [ 4719 23688]]
F1 Score: 0.7380473898210028
Accuracy: 0.7652650975793618
Precision: 0.833878973492449
Recall: 0.6619718309859155
ROC AUC: 0.7651700159113678
Epoch 84 | Train Loss 0.5789551883403744


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31104 12067]
 [ 4746 23717]]
F1 Score: 0.7383068470123119
Accuracy: 0.7652930172822962
Precision: 0.8332572111161859
Recall: 0.6627822490498547
ROC AUC: 0.7651986559056805
Epoch 85 | Train Loss 0.5800852702132293
[[0.3980069 ]
 [0.31516892]
 [0.48818523]
 [0.31509578]
 [0.31123707]
 [0.31192628]
 [0.32270736]
 [0.61258   ]
 [0.81454223]
 [0.32334203]]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3567   72]
 [ 267   93]]
F1 Score: 0.35428571428571426
Accuracy: 0.9152288072018004
Precision: 0.25833333333333336
Recall: 0.5636363636363636
ROC AUC: 0.7469981505192772
Epoch 85 | Test Loss 0.4789862213656306


100%|██████████| 560/560 [01:37<00:00,  5.71it/s]



 Confusion matrix: 
 [[31157 12131]
 [ 4693 23653]]
F1 Score: 0.7376578824263216
Accuracy: 0.7651394589161571
Precision: 0.8344387215127355
Recall: 0.6609937402190923
ROC AUC: 0.7650435925642184
Epoch 86 | Train Loss 0.5794247413852385


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[31176 12094]
 [ 4674 23690]]
F1 Score: 0.7386044771465986
Accuracy: 0.7659212105983192
Precision: 0.835213651107037
Recall: 0.6620277218868769
ROC AUC: 0.76582557642461
Epoch 87 | Train Loss 0.579406535040055


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31160 12070]
 [ 4690 23714]]
F1 Score: 0.7388920047360877
Accuracy: 0.7660328894100566
Precision: 0.8348824109280383
Recall: 0.6626984126984127
ROC AUC: 0.7659377698080626
Epoch 88 | Train Loss 0.5786571902355977


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31103 12051]
 [ 4747 23733]]
F1 Score: 0.7386094858707831
Accuracy: 0.7655024150543038
Precision: 0.8333216292134832
Recall: 0.6632293762575453
ROC AUC: 0.7654082725081311
Epoch 89 | Train Loss 0.5791285020432302


100%|██████████| 560/560 [01:38<00:00,  5.69it/s]



 Confusion matrix: 
 [[31087 12128]
 [ 4763 23656]]
F1 Score: 0.736912605329969
Accuracy: 0.764204148867856
Precision: 0.8324008585805271
Recall: 0.6610775765705343
ROC AUC: 0.7641092206423103
Epoch 90 | Train Loss 0.5804503226386649
[[0.34221634]
 [0.34662813]
 [0.31373096]
 [0.3868514 ]
 [0.3300547 ]
 [0.37674677]
 [0.35462773]
 [0.3140185 ]
 [0.31518355]
 [0.40549538]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3563   70]
 [ 271   95]]
F1 Score: 0.3578154425612053
Accuracy: 0.9147286821705426
Precision: 0.25956284153005466
Recall: 0.5757575757575758
ROC AUC: 0.7525371081709109
Epoch 90 | Test Loss 0.47891759499907494


100%|██████████| 560/560 [01:38<00:00,  5.70it/s]



 Confusion matrix: 
 [[31134 12084]
 [ 4716 23700]]
F1 Score: 0.7383177570093459
Accuracy: 0.7654744953513695
Precision: 0.8340371621621622
Recall: 0.6623071763916835
ROC AUC: 0.7653795296184358
Epoch 91 | Train Loss 0.5795530883861439


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31084 12042]
 [ 4766 23742]]
F1 Score: 0.738567784483295
Accuracy: 0.765362816539632
Precision: 0.8328188578644591
Recall: 0.6634808853118712
ROC AUC: 0.7652690340087948
Epoch 92 | Train Loss 0.5779482690883534


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31134 12067]
 [ 4716 23717]]
F1 Score: 0.7386517588800473
Accuracy: 0.7657118128263115
Precision: 0.8341363908134913
Recall: 0.6627822490498547
ROC AUC: 0.7656170659475214
Epoch 93 | Train Loss 0.5783226279275758


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31236 12182]
 [ 4614 23602]]
F1 Score: 0.7375625
Accuracy: 0.7655303347572382
Precision: 0.8364757584349305
Recall: 0.6595685222445786
ROC AUC: 0.7654327966871429
Epoch 94 | Train Loss 0.579058816869344


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31140 12032]
 [ 4710 23752]]
F1 Score: 0.7394079008809887
Accuracy: 0.7662841667364659
Precision: 0.8345161970346426
Recall: 0.6637603398166778
ROC AUC: 0.7661897933393013
Epoch 95 | Train Loss 0.5774757537458625
[[0.3337515 ]
 [0.36252496]
 [0.3162093 ]
 [0.31468612]
 [0.31134328]
 [0.32570732]
 [0.33650818]
 [0.7466817 ]
 [0.3117134 ]
 [0.3115732 ]]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0 0 0 0 0 0 0 1 0 0]

 Confusion matrix: 
 [[3558   70]
 [ 276   95]]
F1 Score: 0.35447761194029853
Accuracy: 0.9134783695923981
Precision: 0.2560646900269542
Recall: 0.5757575757575758
ROC AUC: 0.7518850476596954
Epoch 95 | Test Loss 0.48153111431747675


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31070 12112]
 [ 4780 23672]]
F1 Score: 0.7370321937854164
Accuracy: 0.7641901890163889
Precision: 0.8319977505974976
Recall: 0.6615247037782249
ROC AUC: 0.7640956852224459
Epoch 96 | Train Loss 0.5791123459381716


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31014 12079]
 [ 4836 23705]]
F1 Score: 0.7370384764865915
Accuracy: 0.7638691124326438
Precision: 0.830559545916401
Recall: 0.6624469036440868
ROC AUC: 0.7637757530772735
Epoch 97 | Train Loss 0.5798484445682593


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[31200 12118]
 [ 4650 23666]]
F1 Score: 0.738408736349454
Accuracy: 0.7659212105983192
Precision: 0.8357818900974714
Recall: 0.6613570310753409
ROC AUC: 0.7658249590523148
Epoch 98 | Train Loss 0.5782033606831517


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[31111 12116]
 [ 4739 23668]]
F1 Score: 0.7374242495053824
Accuracy: 0.7647067035206745
Precision: 0.8331749216742352
Recall: 0.6614129219763023
ROC AUC: 0.7646116213786671
Epoch 99 | Train Loss 0.5789577857724257


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[31129 12094]
 [ 4721 23690]]
F1 Score: 0.7380637121271127
Accuracy: 0.7652650975793618
Precision: 0.8338319664918518
Recall: 0.6620277218868769
ROC AUC: 0.7651700673590591
Epoch 100 | Train Loss 0.5795951812927213
[[0.37583944]
 [0.3217409 ]
 [0.34452656]
 [0.31362948]
 [0.31254685]
 [0.3108663 ]
 [0.31789652]
 [0.39216313]
 [0.31675166]
 [0.3114099 ]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3552   70]
 [ 282   95]]
F1 Score: 0.3505535055350554
Accuracy: 0.9119779944986247
Precision: 0.2519893899204244
Recall: 0.5757575757575758
ROC AUC: 0.751102575046237
Epoch 100 | Test Loss 0.4796637538820505


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31136 12087]
 [ 4714 23697]]
F1 Score: 0.7382817976477919
Accuracy: 0.7654605354999022
Precision: 0.8340783499348844
Recall: 0.6622233400402414
ROC AUC: 0.7653655054455042
Epoch 101 | Train Loss 0.5788937396769013


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31146 12088]
 [ 4704 23696]]
F1 Score: 0.7383771656487598
Accuracy: 0.7655861741631069
Precision: 0.8343661971830986
Recall: 0.6621953945897607
ROC AUC: 0.7654910027342109
Epoch 102 | Train Loss 0.5800722369125911


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31184 12113]
 [ 4666 23671]]
F1 Score: 0.7383228583459397
Accuracy: 0.7657676522321802
Precision: 0.8353389561350884
Recall: 0.6614967583277442
ROC AUC: 0.7656716706562012
Epoch 103 | Train Loss 0.5789489351745163


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[31154 12180]
 [ 4696 23604]]
F1 Score: 0.7366581361962424
Accuracy: 0.7644135466398637
Precision: 0.8340636042402827
Recall: 0.6596244131455399
ROC AUC: 0.7643170880232582
Epoch 104 | Train Loss 0.578499596832054


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31111 12136]
 [ 4739 23648]]
F1 Score: 0.7370307459755964
Accuracy: 0.764427506491331
Precision: 0.8330573854229049
Recall: 0.660854012966689
ROC AUC: 0.7643321668738605
Epoch 105 | Train Loss 0.5780931207750525
[[0.3190761 ]
 [0.40115267]
 [0.31358054]
 [0.45361   ]
 [0.31826475]
 [0.31657094]
 [0.3149619 ]
 [0.32294685]
 [0.31237772]
 [0.31164613]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3576   72]
 [ 258   93]]
F1 Score: 0.3604651162790697
Accuracy: 0.9174793698424606
Precision: 0.26495726495726496
Recall: 0.5636363636363636
ROC AUC: 0.7481718594394651
Epoch 105 | Test Loss 0.4784134468063712


2024/05/05 04:41:33 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmpbjfqe5h6\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[31230 12112]
 [ 4620 23672]]
F1 Score: 0.738872588800799
Accuracy: 0.7664237652511378
Precision: 0.8367029548989113
Recall: 0.6615247037782249
ROC AUC: 0.7663272054455978
Epoch 106 | Train Loss 0.5797693143997874


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31156 12073]
 [ 4694 23711]]
F1 Score: 0.7387870195827946
Accuracy: 0.7659351704497864
Precision: 0.8347474036261222
Recall: 0.6626145763469707
ROC AUC: 0.7658400636267629
Epoch 107 | Train Loss 0.5798265813716821


100%|██████████| 560/560 [01:37<00:00,  5.71it/s]



 Confusion matrix: 
 [[31144 12119]
 [ 4706 23665]]
F1 Score: 0.7377445249785676
Accuracy: 0.76512549906469
Precision: 0.8341263966726588
Recall: 0.6613290856248603
ROC AUC: 0.7650299542489714
Epoch 108 | Train Loss 0.5781684886131968


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[31135 12086]
 [ 4715 23698]]
F1 Score: 0.7382899512438276
Accuracy: 0.7654605354999022
Precision: 0.834054834054834
Recall: 0.6622512854907221
ROC AUC: 0.7653655311693499
Epoch 109 | Train Loss 0.5789699685892888


100%|██████████| 560/560 [01:37<00:00,  5.71it/s]



 Confusion matrix: 
 [[31174 12075]
 [ 4676 23709]]
F1 Score: 0.738954947092833
Accuracy: 0.7661585280732613
Precision: 0.835265104808878
Recall: 0.6625586854460094
ROC AUC: 0.7660631642013868
Epoch 110 | Train Loss 0.5795301229293858
[[0.31569657]
 [0.31557047]
 [0.3143049 ]
 [0.53074425]
 [0.33228716]
 [0.32040364]
 [0.32073286]
 [0.31976122]
 [0.31405804]
 [0.34115398]]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3555   69]
 [ 279   96]]
F1 Score: 0.35555555555555557
Accuracy: 0.9129782445611403
Precision: 0.256
Recall: 0.5818181818181818
ROC AUC: 0.7545241143832693
Epoch 110 | Test Loss 0.4825329966843128


100%|██████████| 560/560 [01:38<00:00,  5.69it/s]



 Confusion matrix: 
 [[31123 12076]
 [ 4727 23708]]
F1 Score: 0.7383484638502624
Accuracy: 0.765432615796968
Precision: 0.8337612097766837
Recall: 0.6625307399955287
ROC AUC: 0.7653378944050168
Epoch 111 | Train Loss 0.5763713129396949


100%|██████████| 560/560 [01:37<00:00,  5.73it/s]



 Confusion matrix: 
 [[31214 12148]
 [ 4636 23636]]
F1 Score: 0.7379792681403771
Accuracy: 0.7656978529748444
Precision: 0.8360215053763441
Recall: 0.660518667560921
ROC AUC: 0.7656010353146308
Epoch 112 | Train Loss 0.5788726241460869


100%|██████████| 560/560 [01:38<00:00,  5.71it/s]



 Confusion matrix: 
 [[31103 12085]
 [ 4747 23699]]
F1 Score: 0.7379417717577457
Accuracy: 0.7650277801044197
Precision: 0.8331224073683471
Recall: 0.6622792309412028
ROC AUC: 0.7649331998499599
Epoch 113 | Train Loss 0.5788088939551796


100%|██████████| 560/560 [01:37<00:00,  5.72it/s]



 Confusion matrix: 
 [[31166 12093]
 [ 4684 23691]]
F1 Score: 0.738509016661731
Accuracy: 0.7657955719351146
Precision: 0.8349251101321586
Recall: 0.6620556673373574
ROC AUC: 0.7657000791359032
Epoch 114 | Train Loss 0.5767615181526967


100%|██████████| 560/560 [01:37<00:00,  5.74it/s]



 Confusion matrix: 
 [[31173 12083]
 [ 4677 23701]]
F1 Score: 0.7387861974377357
Accuracy: 0.7660328894100566
Precision: 0.8351892310945098
Recall: 0.6623351218421641
ROC AUC: 0.7659374353980695
Epoch 115 | Train Loss 0.5798563754452126
[[0.3146133 ]
 [0.31186393]
 [0.39914605]
 [0.32933885]
 [0.31767893]
 [0.6706853 ]
 [0.5481671 ]
 [0.3216714 ]
 [0.31310168]
 [0.31657776]]
[0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3567   73]
 [ 267   92]]
F1 Score: 0.35114503816793896
Accuracy: 0.9149787446861716
Precision: 0.2562674094707521
Recall: 0.5575757575757576
ROC AUC: 0.7439678474889743
Epoch 115 | Test Loss 0.4781075157225132


2024/05/05 04:58:08 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\User\AppData\Local\Temp\tmpunkrzkbg\model\data, flavor: pytorch). Fall back to return ['torch==2.2.1', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback. 
100%|██████████| 560/560 [01:38<00:00,  5.69it/s]



 Confusion matrix: 
 [[31127 12099]
 [ 4723 23685]]
F1 Score: 0.7379424227318045
Accuracy: 0.7651673786190915
Precision: 0.8337440157702056
Recall: 0.6618879946344735
ROC AUC: 0.765072309730068
Epoch 116 | Train Loss 0.5777407485991717


100%|██████████| 560/560 [01:38<00:00,  5.67it/s]



 Confusion matrix: 
 [[31171 12178]
 [ 4679 23606]]
F1 Score: 0.736893037194275
Accuracy: 0.7646787838177401
Precision: 0.834576630722998
Recall: 0.6596803040465012
ROC AUC: 0.7645821324974487
Epoch 117 | Train Loss 0.5793151939553874


100%|██████████| 560/560 [01:38<00:00,  5.67it/s]



 Confusion matrix: 
 [[31129 12096]
 [ 4721 23688]]
F1 Score: 0.7380243951832756
Accuracy: 0.7652371778764274
Precision: 0.8338202682248583
Recall: 0.6619718309859155
ROC AUC: 0.7651421219085784
Epoch 118 | Train Loss 0.5776138976216316


100%|██████████| 560/560 [01:38<00:00,  5.67it/s]



 Confusion matrix: 
 [[31224 12054]
 [ 4626 23730]]
F1 Score: 0.7399438727782974
Accuracy: 0.7671496775274311
Precision: 0.8368599238256453
Recall: 0.6631455399061033
ROC AUC: 0.7670539415011688
Epoch 119 | Train Loss 0.5760394100099802


100%|██████████| 560/560 [01:38<00:00,  5.67it/s]



 Confusion matrix: 
 [[31111 12053]
 [ 4739 23731]]
F1 Score: 0.7386621844554423
Accuracy: 0.7655861741631069
Precision: 0.8335440814892869
Recall: 0.6631734853565839
ROC AUC: 0.765491903068808
Epoch 120 | Train Loss 0.5799134453492505
[[0.31881884]
 [0.39629203]
 [0.85688144]
 [0.3355302 ]
 [0.40845862]
 [0.6289921 ]
 [0.3199279 ]
 [0.3153459 ]
 [0.3120693 ]
 [0.32206655]]
[0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3555   69]
 [ 279   96]]
F1 Score: 0.35555555555555557
Accuracy: 0.9129782445611403
Precision: 0.256
Recall: 0.5818181818181818
ROC AUC: 0.7545241143832693
Epoch 120 | Test Loss 0.48019166104495525


  9%|▉         | 51/560 [00:08<01:41,  5.02it/s]